### ISSUE TITLE
Portal command

### ISSUE THREAD

**Issue by Lokarda2** [sekwah41/Advanced-Portals#105]
Hi,
why a portal like this does not work?

MauvilleBeacon:
  world: Hory
  triggerblock: AIR
  command: '!pex user @player add Mauville'
  pos1:
    X: 444
    Y: 99
    Z: -329
  pos2:
    X: 442
    Y: 95
    Z: -331

It throws out an error about destination. The only thing I want though, is to give a permission after entry

**Comment by sekwah41** [comment]
Which version of the plugin are you using?

**Comment by Lokarda2** [comment]
0.0.38 Snapshot

**Comment by sekwah41** [comment]
Could you give me a screenshot of specifically what message it is giving? The code shouldnt activate if its she piece that is what i think is activating

**Comment by Lokarda2** [comment]
![image](https://user-images.githubusercontent.com/23620484/35834284-5c5cd8a4-0ad5-11e8-9cc8-3e6880f4a982.png)

**Comment by sekwah41** [comment]
OH ok thats wierd, did you set that data yourself? its supposed to be
`command:
  1: '!pex user @player add Mauville'`

**Comment by sekwah41** [comment]
If that doesnt fix it send me another message and I will reopen the issue but that is deffo 1 issue that there is atm

**Comment by sekwah41** [comment]
You reloaded the plugin right? And that deffo is the correct portal? Im gonna take more of a look through the code now

**Comment by sekwah41** [comment]
Oh whoops i got that formatting wrong its like this 
![image](https://user-images.githubusercontent.com/3209834/35837751-ce3bf432-0adf-11e8-81e7-d93c97048a30.png)

**Comment by sekwah41** [comment]
Not how the one was before, command needs to be contained inside portal args
