### ISSUE TITLE
Make destination position relative to where player enters portal

### ISSUE THREAD

**Issue by bc-hill** [sekwah41/Advanced-Portals#108]
As said [here](https://www.spigotmc.org/threads/advanced-portals.102026/page-20#post-2895667),
>It would be cool to be able to make a huge portal, and then have the destination be relative to where you entered the portal. 
So, you make a portal that is 100 blocks wide, and somehow make a destination that is 100 blocks wide.
When you enter the portal at block 75, you exit the destination at block 75.

**Comment by LeotomasMC** [comment]
How would it handle if they are different sizes?

**Comment by sekwah41** [comment]
Due to parts being a little complicated due to different sizes, rotations and all sorts there is a lot of setup that would be needed for a rather specific use case so I am deciding to cancel looking at this for now.
