### ISSUE TITLE
Portal blocks are oriented wrong

### ISSUE THREAD

**Issue by kenjamin80** [sekwah41/Advanced-Portals#115]
The end portal block placer and portal block placer place the portals in the wrong orientation. For the portal block placer (purple) you can indeed punch them to reorient them towards you, but if you place another purple portal next to one that has already been placed, reoriented or not, they both disappear. There needs to be a space between individual blocks for them to stay without disappearing, rendering that block type useless.

As for the end portal block placer, they only face upwards and won't reorient. They are just destroyed when punched with the block.

Please advise

**Comment by sekwah41** [comment]
Create the portal region first and then start placing them. The protection region does this for portals and water to stop it causing issues for natural water and portals.
