### ISSUE TITLE
Add support for multi value/multi tag tags

### ISSUE THREAD

**Issue by sekwah41** [sekwah41/Advanced-Portals#116]
As stated above

**Comment by sekwah41** [comment]
Test this with a randomtp tag as suggested by DeCarvalho

Syntax: 
entrypoint:X,Z(or desti) world:WorldName(if not set use current or one from desti) radius:SetBlocksFromEntryPoint minRadius:(optional) command:CommandToExecute(optional)

if minRadius is set then get the random location as a random angle with a random length in the min to max radius. That or get a random location, normalize the vector (if not in the range) (use rather than angle random) and then do the random length.

**Comment by DeCarvalho83** [comment]
Really nice, whenever the feature is up id like to make tests :D and report as many bugs as possible :D 
just cuz i like to find bugs pushing hard :D 
im dev not dev too so i know how 'annoying' finding bug things may be

Thanks for considering my idea

**Comment by sekwah41** [comment]
The plugin is going through a sorta re-recode :P Some of the things i started I had planned ages ago with the recode but we have a new layout we are moving everything to as @Rezel has been prodding me with a stick to improve my coding and so far its a hell of a lot cleaner :)

Hopefully you should see some working versions for spigot pretty soon after my exams are done and forge maybe not too long after tho its not a prio though I dont think the forge version is so much your interest is it? xD

**Comment by DeCarvalho83** [comment]
Oh no forge is far from it.. since im running almost 100 plugins right now and most arent supported by forge/sponge.. 
i'll stick with spigot :P

Once again, good luck there..
iTs my finals @ college too..
