### ISSUE TITLE
permission setting is not work

### ISSUE THREAD

**Issue by Arthurdes** [sekwah41/Advanced-Portals#12]
CraftBukkit version git-Bukkit-624c97f (MC: 1.8.3)
AdvancedPortals v0.0.5
PermissionsEx v1.23.1

Create the portal like this
/portal create name:test desti:a01 triggerblock:AIR permission:art.test

then give permission node "art.test" by PermissionsEx
player still can't use test portal
display:[AdvancedPortals]You do not have permission to use this portal

**Comment by sekwah41** [comment]
I will check this, we didnt do full tests for this. When i have some free time I will fix is as soon as possible.

**Comment by sekwah41** [comment]
This seems to be part of a larger issue messing up permissions for all portals even if you dont use the tag.

**Comment by sekwah41** [comment]
Problem found and solved, will upload an update shortly.
