### ISSUE TITLE
AdvancedPortals is not working

### ISSUE THREAD

**Issue by LegendOfPeanuts** [sekwah41/Advanced-Portals#122]
See the title, it is not working. Whenever I start the server with advanced portals installed, it freezes the server and my server didn't start.
Here is the full log until the server freezes:
https://pastebin.com/uVxyGGmG

**Comment by sekwah41** [comment]
There is an error from the world plugin but nothing advanced portals is doing should be able to freeze like that from what I remember. I will double check later and see if I can find where it would freeze.

Could you try and see if it freezes on that system when it is on its own?

**Comment by LegendOfPeanuts** [comment]
It is working with a test server

**Comment by sekwah41** [comment]
Try deleting the folder it makes and see if it works then
