### ISSUE TITLE
1.8.3 not working

### ISSUE THREAD

**Issue by Future-Force** [sekwah41/Advanced-Portals#13]
i created a destination portal in world 1 then i created a portal in world 2 with destenation world1.

when i move anywhere on anymap i fly up and i cant stop have to reboot server ?

**Comment by sekwah41** [comment]
Try deleting the portal file and remake the portals, could be you selected a giant region by mistake. If the problem persists ill take a look into it as it is probably a bug.

**Comment by sekwah41** [comment]
I will assume the problem has been solved due to no reply, crash logs or enough info to replicate the problem. If the problem persists then please open a new issue.

**Comment by kasperbjerby** [comment]
I am having this problem too :/
