### ISSUE TITLE
Option to delay portal teleport destination a few ticks.

### ISSUE THREAD

**Issue by mibby** [sekwah41/Advanced-Portals#131]
Would it be possible to delay the teleport a few ticks? Or perhaps loading of entities a few ticks? Advanced Portals seems to teleport players faster than nearby npcs can load so they load in without any skin. Using Citizens for npcs near one of the teleport destinations configured. 

If I teleport away with ```/spawn``` and then warp normally via a command (i.e. ```/warp area```), the npcs load their skins properly. It's only when using the advanced portal where you get teleported faster than npcs can load - so some npcs don't retain their skin.

**Comment by sekwah41** [comment]
Which warp command is this? advanced portals or another plugin. Advanced portals just does a generic teleport call which if anything it should be the problem of spigot or that plugin but I will look into it.

**Comment by mibby** [comment]
EssentialsX's warp command. Same with using EssentialsX back and home commands, tping into an area with npc entities. Essentials seems to tp players into new chunks fine with npcs loading their skin a second afterwards, while AdvancedPortals teleports players _seems to_ teleport players before the npcs load, resulting in some skins never getting sent to the client in time.

**Comment by mibby** [comment]
It might have something to do with the npcs being on a chunk border at the sides of a player. I moved them in front in the middle of a chunk when loading in and they seem to load smoother now with AdvancedPortals.

**Comment by sekwah41** [comment]
Ill take a look at the warp code to see if they are doing anything different :)

**Comment by sekwah41** [comment]
Based off the fact this is a pretty generic teleport with the setlocation this should just work fine. Sorry for not looking at this in a while but I would suggest contacting the dev of npc's. If he suggests a change I should make to add compatibility I will be more than happy to oblige.
