### ISSUE TITLE
Cross-world Ridden Entity TP

### ISSUE THREAD

**Issue by Nerdcrafteria** [sekwah41/Advanced-Portals#135]
Hello!

Spoke with you via discord pms (PerfectFlaw). Looking for support for cross-world ridden entity warps. We're currently running Multiverse Core in case that makes a difference. 

Thanks a bunch!

**Comment by seema84** [comment]
why was "WarpRiddenEntity" removing in 1.13?
please add a full tameable entity support (with "and" without riding)

**Comment by sekwah41** [comment]
For entities riding you I think its fine but the issue is client side due to some camera problems and it's tricky. I'll see what client tricks I can do to stop the camera issues we were having in the past.

**Comment by sekwah41** [comment]
Due to issues with both teleportation long distanced and as well as cross world this will be ignored for now.
