### ISSUE TITLE
[IMPORTANT] Make this plugin compatible with NoCheatPlus

### ISSUE THREAD

**Issue by Lou363** [sekwah41/Advanced-Portals#14]
Hello,
On my server NoCheatPlus keep detecting that players are cheating while crossing portals. Please update and use the NoCheatPlus API to fix this annoying glitch.

**Comment by sekwah41** [comment]
Noted, ill take a look and add support

**Comment by Lou363** [comment]
Thank you very much. I forget to tell you that because NoCheatPlus is freezing the player and AP keep trying to teleport the player. The server instantly crash.

**Comment by sekwah41** [comment]
The api was not needed, just made the server change the event data saying if the player teleported they were always there so NoCheatPlus believes they haven't moved at all.

**Comment by Lou363** [comment]
What do you mean? What do I need to do to fix it?

**Comment by sekwah41** [comment]
I have released a new build to bukkit, just download it and it should work.

**Comment by Lou363** [comment]
Thank you, I'll try tomorrow and I will reply to say if it did work or not.

**Comment by Lou363** [comment]
I have tried it and it dosen't work on my Minecraft 1.7.9 R0.1 server if you need to, I have recorded a video showing what happen from A to Z. It is only 18 seconds long.

Thank you.

**Comment by sekwah41** [comment]
Thats odd, I swear I got it working yesterday

**Comment by sekwah41** [comment]
Found the problem, the bug is only fixed for air portals at the moment. As soon as I have found the solution I will upload a new version.

Ill keep you up to date on the progress of the fix on the other portals here.

**Comment by sekwah41** [comment]
This time its linked into nocheatplus and has been tested with normal portals too this time

**Comment by sekwah41** [comment]
A lot of odd stuff seems to happen when you go through a portal which isn't air. Ill take a look when i can and keep trying.

**Comment by sekwah41** [comment]
The problem has finally been fixed. I will push the update either today or tomorrow.

**Comment by sekwah41** [comment]
Finally found the problem and it seems it was my fault, the code was calling the wrong event and causing a giant loop which ncp was glitching out because it was being recalled after the teleport with the same data. Anyway it has been fixed now and as far as I can tell there are no longer any problems. The fix should be uploaded tomorrow.

**Comment by sekwah41** [comment]
Sorry for the error by the way, I know that must have caused a lot of frustration. I know it was annoying me trying to fix it xD

**Comment by Lou363** [comment]
Thank you I am looking forward to the next update! I will be very happy to uninstall creative gate (it is rubbish) and your plugin is a lot easier and much more customization.

**Comment by sekwah41** [comment]
There is a glitch with 1.8.8 for some reason though, no idea why though. As soon as you make a portal it starts warping you into the sky. Just be careful which bukkit or spigot version your using.

**Comment by sekwah41** [comment]
This bug has also been fixed.
