### ISSUE TITLE
End Gateway Portals in End

### ISSUE THREAD

**Issue by zQuark** [sekwah41/Advanced-Portals#142]
When using End Gateway as Triggerblock in the End, the Vanilla teleport will take precedence over the Portals teleport, so even when setting the destination of the Vanilla gateway to itself, Portals won't take action as the gateway triggers the 'wait 3 seconds' so you just stand there is the portal, nothing happening

**Comment by sekwah41** [comment]
Ill take a look and see what event that triggers, that should hopefully be quite the easy fix.

**Comment by sekwah41** [comment]
I dont believe this is an issue anymore, feel free to correct me if im wrong
