### ISSUE TITLE
/spawn triggers the start of the PortalCooldown

### ISSUE THREAD

**Issue by Aero4K** [sekwah41/Advanced-Portals#146]
I'd like the cooldown for my portals to be self-contained, however my /spawn command (which comes from a completely different plugin) is causing the PortalCooldown timer to start counting down.

My server runs the latest version of Paper, using CMI for essential commands.

**Comment by sekwah41** [comment]
This was added because of command portals though I can look to add it only to trigger on commands activated from the portals if you want.

**Comment by sekwah41** [comment]
I know its been a while though I would recommend lowering portal cooldowns. The whole point of the portal cooldown is top stop people being teleported into portals as the result of a plugin or spawning in them.
