### ISSUE TITLE
[Enhancement] Allow multiple triggerblocks or wildcard

### ISSUE THREAD

**Issue by Lachney** [sekwah41/Advanced-Portals#148]
This plugin is super neat! I'd really like to set the trigger block to be multiple blocks (the trigger would just stepping into the portal region). Playing around with this plugin on Spigot+Forge server wanted to use modded blocks. :P

**Comment by sekwah41** [comment]
This is in the recode but I have a few projects before I finish that as its half done. Though I could backport the feature possibly

**Comment by Lachney** [comment]
@sekwah41 Super awesome, looking forward to seeing it. Thank you much.

**Comment by sekwah41** [comment]
Has been added in the latest code. This will be released soon. You can add as many as you want though there is not a wildcard.

**Comment by sekwah41** [comment]
You can download it from here for now https://share.sekwah.com/Advanced-Portals-0.0.52-snapshot.jar

**Comment by Lachney** [comment]
Oh sweet, thank you so much @sekwah41 !
