### ISSUE TITLE
enhancement: Support Multi-language

### ISSUE THREAD

**Issue by Nogapra** [sekwah41/Advanced-Portals#158]
Be able to customize the help and error messages in the language of our choice.
I use this plugin for several years and I have no problem with English, but having recently departed from an exclusively French community my staff would like to have error messages and help translated into French
King regards

**Comment by sekwah41** [comment]
This has already been coded in the recode though I need to finish that.

**Comment by sekwah41** [comment]
Code is done so closing issue. Though I have been busy with other projects. Will revisit it soon due to being free from uni now.

Though this one is already complete.
