### ISSUE TITLE
Fix for chunk cache?

### ISSUE THREAD

**Issue by MrLava13** [sekwah41/Advanced-Portals#162]
Hello, when moving to another server, the chunks and holograms from the previous server. Both servers are running paper spigot 1.13.2 and both are having the same issue.
![Screen Shot](https://user-images.githubusercontent.com/24940520/60449247-74723000-9be4-11e9-9906-0fd55fde700f.png)

**Comment by sekwah41** [comment]
This is a bungee issue, Advanced Portals has 0 control over this and its not possible for me to have control over it.

If you need any info for the bungee guys this is the message sent to bungee.

```Java
ByteArrayDataOutput out = ByteStreams.newDataOutput();
            out.writeUTF("Connect");
            out.writeUTF(bungeeServer);
            portal.inPortal.add(player.getUniqueId());
            player.sendPluginMessage(plugin, "BungeeCord", out.toByteArray());
```
