### ISSUE TITLE
1.15 Ready?

### ISSUE THREAD

**Issue by soerili** [sekwah41/Advanced-Portals#172]
Is this plugin 1.15 ready?

**Comment by sekwah41** [comment]
Should be unless there were major changes to the spigot API. Though I can test it when I get time tomorrow.

**Comment by RedFirebreak** [comment]
After testing, the plugin does not seem to be compatible with 1.15 yet.
It does load the plugin without errors. Upon creating a portal, it gives an error however.

**Comment by sekwah41** [comment]
Ah ok, I will update this plugin in the next day or two

**Comment by natr566** [comment]
Just a quick one on this i have tested it on 1.15.1 and its seems to work great.

**Comment by sekwah41** [comment]
Just checked and cant find the errors @RedFirebreak. I will close this issue for now though could you open an issue with the crash you had please?
