### ISSUE TITLE
Portal Region Selector acts as normal axe

### ISSUE THREAD

**Issue by gamerBruh** [sekwah41/Advanced-Portals#173]
When trying to use a portal region selector with version 0.2.0 on 1.14, the selector does nothing with right click and breaks with left click.

**Comment by sekwah41** [comment]
Please ensure that the following settings are in the config


# Set to true if you want the normal axes to work normally but the ones gived with /portals selector or wand will still work though
# It can be usefull if people with permission want to use an iron axe on a survival server
UseOnlyServerMadeAxe: false

# Preferably an item and not a block but it shouldnt matter
AxeItemId: IRON_AXE


Also do you have any plugins like worldguard that may be taking over the break events?
