### ISSUE TITLE
destination not set while switching bungee servers

### ISSUE THREAD

**Issue by chrissamael** [sekwah41/Advanced-Portals#179]
I've read that this is a feature, but somehow this is not working for me. I'm using the latest paper and waterfall builds paired with v0.3.0-snapshot, and set up 3 paper servers with portals going between them. each portal has a valid destination on the server it's sending me to, yet it spawns the player on his last position on that server.

**Comment by Mintaka3a** [comment]
Confirmed to also be happening on the latest versions of BungeeCord and Spigot (Jenkins build 2667) on April 20, 2020.  Cross-server ports are working but the specified destination that has been configured for a portal is ignored and the player ends up at their last known location in the world being ported to.

Should something be installed in the BungeeCord plugins folder to help facilitate a successful port from one server location to another?

**Comment by sekwah41** [comment]
This was only added in the latest versions of the plugin 0.4.0 and above. However I fixed a major bug with that feature today which was because the pr that added  it got the uuid's from the servers rather than using connections to identify players which obviously fails when ip-forwarding and bungee support are disabled in the setup.

Check out https://github.com/sekwah41/Advanced-Portals/releases/tag/0.5.0

**Comment by sekwah41** [comment]
Actually I will leave this open until it has been verified if this is the issue or not.

**Comment by Mintaka3a** [comment]
Absolutely stunning!  The extremely high reputation of this plugin, and of sekwah41 in particular, really are truly deserved!  I reported the problem this morning, quite frankly half-expecting to never hear anything back whatsoever, and yet in a matter of just a few hours you've published a new version that fixes the problem completely!  I can now confirm that Advanced Portals 0.5.0 definitely allows players to port to the correct previously defined location on *different* servers in a BungeeCord cluster.  I have also confirmed that you can even have users port from the overworld on one server to The Nether on another server!  Sheer brilliance!

I would like to tip you $100 as a token of my appreciation, but the donation link (https://ko-fi.com/sekwah41) on the Advanced Portals Spigot page (https://www.spigotmc.org/resources/advanced-portals.14356/) no longer works.  Please advise how we, the appreciative users of your wonderful plugin, can support you now.

For the benefit of other users, please note what sekway41 states - the same Advanced Portals jar file MUST be copied into the plugins folder of all Spigot servers in the BungeeCord cluster AND into the plugins folder of the BungeeCord instance as well.  There isn't a separate jar file for BungeeCord - very clever!  Personally, I use symbolic links myself so I only have to update one file when a new version of any shared plugin is updated.

**Comment by sekwah41** [comment]
First off, I have updated the plugin description to note about that. Feel free to suggest any changes that need to be made :)

Secondly I completely forgot about the donation link... I changed it to just sekwah a while back as I don't know why i started as sekwah41 when sekwah was free most places xD

I've updated the link on spigot https://ko-fi.com/sekwah

You have made my day. I have never received a donation of this size for anything I've done o-o

**Comment by Mintaka3a** [comment]
I see now that you've got two different donations links - would you prefer people use the ko-fi link or the PayPal one?  In other words, which one keeps the least amount of your donations for themselves! ;)

**Comment by sekwah41** [comment]
They both end up going through paypal, though I am unsure how paypal processes ones it sees as donations which is what the paypal direct link one does.

**Comment by sekwah41** [comment]
I just want to check you meant to send £100 and not $100 right? I don't want to be taking extra money by mistake.

**Comment by Mintaka3a** [comment]
It's fine, PayPal prompted for UKP by default and I didn't want to be pedantic and send you £80.93!  I'm a UK freelance software developer myself and charge 50UKP/hour, so it still feels like I'm benefiting immensely from your great plugin yet I've only paid you for two hours work to create it!

Consider the extra a little incentive to get the auto-complete of destination names on other servers working! ;)

**Comment by sekwah41** [comment]
It's an incentive to finish the recode once my uni is done in the next month or so ;)

I am a software developer myself though as I'm at uni it's just a part time contract for Fujitsu.

Still gotta figure out what I'm gonna generally do after all this. Hopefully you'll enjoy the new API I've made if you end up needing anything custom.

**Comment by Mintaka3a** [comment]
Hello again,

Very sorry to report that this bug has re-appeared. :(

Same as last time: Cross-server ports are working but the specified destination that has been configured for a portal is ignored and the player ends up at their last known location in the world being ported to.

Using AdvancedPortals-0.5.8-snapshot.jar on BungeeCord and all associated Spigot servers.

Hope you can help again!
