### ISSUE TITLE
Portal Protection Radious is fixed on 5 and changing config value makes no difference

### ISSUE THREAD

**Issue by efindus** [sekwah41/Advanced-Portals#183]
As stated above when I change Portal Protection Radious in config to lets say 2 the in game Portal Protection Radious, even after rebooting server is still 5. I am using the newest version.

**Comment by sekwah41** [comment]
Which version of minecraft is this with and what are you using to run the server?

**Comment by sekwah41** [comment]
I've just opened the latest spigot and version to verify behavior. The blocks go 1 larger in the + axis of every direction so its a little lopsided (will need to fix) however changing the protection radius fully seems to work. Please try deleting your config, allowing it reset and then check the behaviour.

**Comment by efindus** [comment]
Ok. Will try. I am using PaperMC 1.15.2.

**Comment by efindus** [comment]
Ok. Letting plugin regenerate config helped. Everything works now.
