### ISSUE TITLE
Allow to set cooldown per portal

### ISSUE THREAD

**Issue by Testerro** [sekwah41/Advanced-Portals#184]
Allow to set cooldown per portal instead of global cooldown (from config) for all portals.
This will make portals more flexible in case when user wants to make other portal to be used more rarely/often than others.

**Comment by sekwah41** [comment]
I will accept this solution once as long as it doesn't break current intended functionality which was to stop people accidentally entering portals on world enter. This would break a lot of servers current intended functionality as it is to satisfy a few use cases. (I have given more info on the pr review)

**Comment by sekwah41** [comment]
The pr has been merged and this will be released in the next update later
