### ISSUE TITLE
Wrong player gets sent to desti on server portal warp

### ISSUE THREAD

**Issue by silicondev** [sekwah41/Advanced-Portals#189]
Related to #187 

When a player uses a portal to go from one server to another, a player on the destination server will be sent to the specified desti and not the player using the portal.

Sorry to bother you again with another bug, I was going to see if I could find the bug in the code and propose a change myself but I couldn't find the player warp code.

Thanks,
Silicon

**Comment by sekwah41** [comment]
oh silly me, I forgot to remove part of the statement someone else wrote

`event.getPlayer().getServer().getInfo().sendData(plugin.channelName, out.toByteArray());`

i believe should be
`event.getPlayer().sendData(plugin.channelName, out.toByteArray());`

Otherwise it uses any old connection

**Comment by sekwah41** [comment]
This should fix it https://github.com/sekwah41/Advanced-Portals/releases/tag/0.5.2

Sorry for any inconveniences.
