### ISSUE TITLE
portal block wand creation

### ISSUE THREAD

**Issue by KrohmKoala** [sekwah41/Advanced-Portals#19]
What do you think about a function whose set a portal at the position of the player for circle or triangle portal or custom portal ? it's just what AncientGates plugin do but it's an outdated plugin :)

**Comment by sekwah41** [comment]
So you mean build a premade portal where you are standing?

**Comment by KrohmKoala** [comment]
not really, you build a frame and the portal is set in this frame. Have you already use AncientGates ?

**Comment by sekwah41** [comment]
I have never used it. I will have to take a look. I may also have it so you can use the portal selector like a world edit axe but for portal blocks.

**Comment by KrohmKoala** [comment]
i don't really understand what you mean ^^

**Comment by sekwah41** [comment]
you select a region, and it will turn it to portal blocks

**Comment by KrohmKoala** [comment]
now i understand :D

**Comment by sekwah41** [comment]
Kind of forgot what exactly was going on here.  Sorry it seemed to be fixed anyway.
