### ISSUE TITLE
Cooldown variable.

### ISSUE THREAD

**Issue by mibby** [sekwah41/Advanced-Portals#190]
Would it be possible to add a cooldown variable so Advanced-Portals isn't spamming commands? I had a Bungee type portal spam forward me to another server and it saying I was already connected to that server. I believe AP tried to run the command multiple times.

I would like to add a cooldown so AP only attempts commands / movement / teleporting / forwarding once before trying again if still inside the portal area.

**Comment by sekwah41** [comment]
there is already a cooldown tag

**Comment by mibby** [comment]
Does the cooldowndelay work for teleport / traversal though? Or just commands. The config variable for cooldown is only when teleporting / joining. It doesn't prevent Advanced-Portals from spamming actions if the player is inside the portal region, as evidence by Bungee attempting to send them to another server twice. 

I just want the portal to attempt traversal once, then go on cooldown.

**Comment by sekwah41** [comment]
I can check tonight or in the next few days as someone else implemented the cooldowns I don't know them off the top of my head. The intended behaviour would be activation which would be any successful run of the portal if that be commands, bungee or destination.

**Comment by sekwah41** [comment]
From what ive seen of testing locally unless  you are using an old version this should be fine
