### ISSUE TITLE
Triggerblock nether_portal sometimes teleports you to the nether

### ISSUE THREAD

**Issue by jinkhya** [sekwah41/Advanced-Portals#191]
Hello,
when using nether_portal as trigger block to teleport to a different world, it sometimes teleports the player to the nether. Not a consistent bug, sometimes it does teleport me to the right location. 

To be sure it was the nether_portal doing it and nothing else I made the portal with water as trigger and the issue was gone

Do note that using nether_portal trigger in the second world (so not overworld) does not teleport you to the nether. So it only happens when traveling from the overworld.
I hope it all makes sense :)

version : Advanced-Portals-0.5.2-snapshot.jar on 1.15.2

**Comment by sekwah41** [comment]
It may be with local latency though I don't seem to be able to replicate this issue with 0.5.3. Try to make sure that the region surrounding the portal is larger than the portal if you are having an issue with this in edge cases and see if it is still happening :)
