### ISSUE TITLE
Going into a portal while riding a pet gives an error and freezes(MyPet)

### ISSUE THREAD

**Issue by Dimitar0w0** [sekwah41/Advanced-Portals#193]
Hello, I'm using The plugin MyPet and when I go into a portal while riding/flying a pet i freeze and have to reconnect to the server to be able to move. Can you have a look at the console and tell me if it's something from Advanced-Portals that can be fixed or it's just MyPet's fault. When I use Multiverse-portals only I teleport and the pet just despawns and spawns with me. But personally I like AP more and it would be cool if it was fixed :).
![image](https://user-images.githubusercontent.com/32715048/83328673-7e396300-a28d-11ea-9445-731bb258fdd2.png)
![image](https://user-images.githubusercontent.com/32715048/83328718-cb1d3980-a28d-11ea-9949-ee64b209d835.png)
Thank you!

**Comment by sekwah41** [comment]
Thats an error with the mypet plugin. They are handling something wrong on their end with the entity code.
