### ISSUE TITLE
Protection size

### ISSUE THREAD

**Issue by MrPinguK** [sekwah41/Advanced-Portals#196]
Hello, I am in my own small server and some of the players on it don't have op but are not allowed to build where the portals have been made, is there any way to make the portal protection smaller?
thanks.

**Comment by sekwah41** [comment]
I meant to look into a similar issue yesterday. I'll look into it today or tomorrow if I get time.

**Comment by sekwah41** [comment]
There is an option in the config called PortalProtectionArea. There is also a way to disable it all together which is broken and i have fixed now. It will be in the next update but you should be able to alter the area.
