### ISSUE TITLE
Selector has stopped working

### ISSUE THREAD

**Issue by ZeeRaider** [sekwah41/Advanced-Portals#199]
I love the plugin and have been using it for the past couple of weeks.
For some reason, in the last few hours the portal selector has stopped working.
I can select Point 1 and Point 2 but then when I go to create the portal, it just tells me that I need to select two points. Very strange!
I've just updated to the latest build and still no success.

**Comment by sekwah41** [comment]
Are you using the iron axe or have you started using a world edit axe? (sorry if its a stupid question i just had to ask as they are both axes :P)

Which version of the plugin are you using and what version of spigot including if its a separate branch such as paperspigot.

**Comment by ZeeRaider** [comment]
I'm using the latest PaperMC but this supports the latest Spigot )I've never known it not be compatible with plugins). It did however work until today. 
As for the tool, I'm using the Iron Axe.
Can you use the world edit wand? I'm desperate to get back to Ultimate Portals, I've had to install Multiverse Portals but, UP is far better.
I appreciate the reply :)

**Comment by sekwah41** [comment]
Sorry but just to check where did you download this plugin from? Could you link me to the download page?

Also if its only a recent issue it could be a plugin affecting the selection code so could you list the plugins you are using?

**Comment by ZeeRaider** [comment]
Originally from Spigot https://www.spigotmc.org/resources/advanced-portals.14356/
I also tried directly from my admin panel in multicraft.

All the existing portals continued to work, the only thing that stopped working was the selector tool.

I just reinstalled again and tried with the wand from WE and still no success.

**Comment by sekwah41** [comment]
The world edit wand won't work. The main issue I can think it if you have an intrusive mod to events like worldguard cancelling the events in the area. I try to be as light as I can with the events so ignore them if another one takes over to try to improve compatibility. Though I assume a plugin is messing with it.

**Comment by ZeeRaider** [comment]
| Up |   |   |   |  
-- | -- | -- | -- | -- | --
  |   | AdvancedPortals | Directory | 4 KB | Jun 23 09:04 |  
  |   | Autorank | Directory | 4 KB | Jun 12 17:06 |  
  |   | CommandPanels | Directory | 4 KB | Jun 12 02:35 |  
  |   | CoreProtect | Directory | 4 KB | Jun 23 09:26 |  
  |   | DiscordSRV | Directory | 4 KB | Jun 10 18:04 |  
  |   | EntityTrackerFixer | Directory | 4 KB | Jun 22 10:03 |  
  |   | Essentials | Directory | 4 KB | Jun 23 04:48 |  
  |   | EssentialsGeoIP | Directory | 4 KB | Jun 09 23:24 |  
  |   | EssentialsXMPP | Directory | 4 KB | Jun 09 23:24 |  
  |   | GriefDefender | Directory | 4 KB | Jun 23 09:04 |  
  |   | GriefPreventionData | Directory | 4 KB | Jun 09 23:34 |  
  |   | Hackercage | Directory | 4 KB | Jun 15 14:04 |  
  |   | LuckPerms | Directory | 4 KB | Jun 09 23:33 |  
  |   | Multiverse-Core | Directory | 4 KB | Jun 18 20:08 |  
  |   | Multiverse-Inventories | Directory | 4 KB | Jun 18 20:09 |  
  |   | Multiverse-NetherPortals | Directory | 4 KB | Jun 23 08:00 |  
  |   | Multiverse-Portals | Directory | 4 KB | Jun 23 08:00 |  
  |   | MyCommand | Directory | 4 KB | Jun 17 23:33 |  
  |   | PlaceholderAPI | Directory | 4 KB | Jun 18 00:56 |  
  |   | PluginMetrics | Directory | 4 KB | Jun 09 23:10 |  
  |   | Rankup | Directory | 4 KB | Jun 17 22:58 |  
  |   | ServerlistMOTD | Directory | 4 KB | Jun 17 06:47 |  
  |   | Ultimate_Economy | Directory | 4 KB | Jun 20 20:19 |  
  |   | Updater | Directory | 4 KB | Jun 09 23:48 |  
  |   | Vault | Directory | 4 KB | Jun 09 23:16 |  
  |   | VoteNight | Directory | 4 KB | Jun 18 08:28 |  
  |   | WorldEdit | Directory | 4 KB | Jun 18 21:37 |  
  |   | bStats


That’s the full list haha. 
Possibly Grief Defender I guess if you think it’s a permission override error. It was working until today though

**Comment by sekwah41** [comment]
Are there any new plugins that were added when it stopped working? Or did it just stop working? It seems a bit odd to suddenly stop unless there was a change.

**Comment by ZeeRaider** [comment]
No new plugins, I do keep my plugins up to-date as much as possible and two that were updated were Grief Defender and Luckperms.
I agree that it's strange for it to stop working without a change. That's why I'm reaching out really.

I'm ok with using Multiverse Portals, I just prefer UP and thought that maybe it was a known error.

**Comment by sekwah41** [comment]
I would recommend disabling Grief Defender temporarily to test and if that turns out to be the case I can possibly make the event capturing a little more aggressive. Though also make sure that the user has the permission `advancedportals.createportal`. Other than that the only thing I could think of to test would be to reset the  AdvancedPortals config.yml

**Comment by ZeeRaider** [comment]
I’ll try disable GD later on when I get to the server and report back on the result.

As for the permissions, yep - I’ve made sure that my admin account has that. They have full permissions.

As for the config.yml - I tried going into this and seeing if anything was set incorrectly form my side or if anything could be changed to see if the output was different. I guess the only thing I didn’t try was binding to a different tool, I just don’t see what difference that could have made.

That said, I’m willing to try all sorts to troubleshoot.

**Comment by sekwah41** [comment]
Did you end up finding any more info relating to this issue?

**Comment by sekwah41** [comment]
Ill have to assume this was a plugin compatibility bug for now. Feel free to reopen the issue if you find anything new
