### ISSUE TITLE
Can't get portal block :/.

### ISSUE THREAD

**Issue by DeadXToGo** [sekwah41/Advanced-Portals#20]
There's a litte problem with the /portal portal command.
If I type it, the chat says "You have been given a Portal Block!" but I don't get one :/.
There's no error in the console and I'm using the latest version of spigot.

**Comment by sekwah41** [comment]
It is a problem only in 1.8. It is physically impossible to get the portal block as an item in your hand now or at least the old way doesn't work. I will replace it with purple panes or purple woll with a special name which when placed will be automatically be replaced with portal blocks.

**Comment by sekwah41** [comment]
Really needs to get done. Will be one of the next important features to add.

**Comment by sekwah41** [comment]
Finally updated, will be released later
