### ISSUE TITLE
Plugin Issue

### ISSUE THREAD

**Issue by Eilrahcrrod** [sekwah41/Advanced-Portals#210]
I downloaded a plugin called CraftEnhance on Craftbukkit for my minecraft server. link to the plugin: https://dev.bukkit.org/projects/craftenhance
I've used this plugin for a while and only had issues since I updated the server and the plugin to 1.16.1. When I try to do the main command (/ceh) it gives me the message "[CraftEnhance] Could not execute the command." Followed by "An internal error occurred while attempting to perform this command"
when I use /pl to see the plugin list it shows its disabled.
Here's what the log says: https://pastebin.com/chZNxQcF

I also submitted it to the bukkit page but I am yet to get a response and it's been a while.

**Comment by Eilrahcrrod** [comment]
just realized I put this under the advanced portals issue

**Comment by sekwah41** [comment]
You are on completely the wrong project. I see nothing in this issue related to Advanced Portals at all.

**Comment by Eilrahcrrod** [comment]
Oh sorry. I didnt realize. I just hit the New Issue button thinking it would make a new issue

**Comment by sekwah41** [comment]
Oh that's what it does. Just need to make sure you are on the right project first 🤣

You want https://github.com/DutchJelly/CraftEnhance/issues
