### ISSUE TITLE
EssentialsX spawn on join overriding destination

### ISSUE THREAD

**Issue by james090500** [sekwah41/Advanced-Portals#214]
When using EssentialsX and having "spawn-on-join" set. Players will be sent back to spawn after using a portal to a cross server destination.

Essentials config
```YAML
spawn-join-listener-priority: lowest
spawn-on-join: true
```

**Comment by sekwah41** [comment]
That is not an issue with advanced portals but rather how EssentialsX works. Theoretically Advanced portals should trigger after it if done correct.

**Comment by james090500** [comment]
Any guidance on how to get AdvancedPortals to trigger after it?

**Comment by sekwah41** [comment]
It triggers with a delay when the user joins. There isn't anything specific about it sadly. If they are both triggering with the onjoin event you can recompile advanced portals with an event priority or I can take a look at that in the next few days to try to get it to trigger after essentials.

**Comment by sekwah41** [comment]
Actually taking a look into EssentialsX there is a Join priority setting or something somewhere https://github.com/EssentialsX/Essentials/blob/1be3daf0b505d88e37ed166df5fc04d38a7934ed/EssentialsSpawn/src/com/earth2me/essentials/spawn/EssentialsSpawn.java#L47

By the looks of that try setting it to lowest and see if it changes the order. If that doesn't work try highest. By default events usually go in the middle from what I remember.

**Comment by sekwah41** [comment]
Try taking a look in the settings file and see if there is anything there.

**Comment by james090500** [comment]
Unfortunately I already tried that, it was in the original post.

**Comment by sekwah41** [comment]
Ah sorry im having to deal with support tasks at work too. Can you try highest and see if that changes anything? For different tasks it means different things quite a bit.
