### ISSUE TITLE
endportals give lagspikes

### ISSUE THREAD

**Issue by Gerbildral** [sekwah41/Advanced-Portals#215]
i would like to make a portal with endportal blocks.
but when i try the command /portals endportalblock it gives me error all over the place. [log](https://pastebin.pl/view/da5e92e3)

we are running on the latest spigot paper build in 1.16.1

**Comment by Gerbildral** [comment]
ps, the end etc. are disabled so we dont teleport to there

**Comment by sekwah41** [comment]
Given the fact that the error you are listing is from giving you the block and its specifically this line causing the error https://github.com/sekwah41/Advanced-Portals/blob/42b01ec05986227a3a0221ea2ede0e7e94f93fa8/src/main/java/com/sekwah/advancedportals/bukkit/AdvancedPortalsCommand.java#L167

Despite what their warning says there I'm fairly certain it is an issue with Paper. Try using regular spigot and see if the issue persists. That one line unless implemented wrong on their end or altered by some "efficiency boost" they have should never cause recursion like that.

**Comment by sekwah41** [comment]
If this is still being a problem on spigot itself I will happily look into it. Though I keep seeing issues with Paper from people falling through the world to stuff like this so I personally wouldn't recommend it.

**Comment by Gerbildral** [comment]
Thanks for your answer, i tried with spigot then the error where gone but still got lagg spikes and with spigot 1.16.2 too and even in single player i got lagg spikes so its probably an minecraft bugg. I hope it will be fixed soon.

**Comment by sekwah41** [comment]
Good point, given the stack trace is looping on mc code its either how the API talks to the Mojang code or a bug with Mojang's code.
