### ISSUE TITLE
command doesnt do anything

### ISSUE THREAD

**Issue by kennethvd1997** [sekwah41/Advanced-Portals#217]
i installed the api on my fresh spigot server mc1.16.1 and i type :/desti create test and there is no answer. 
and the terminaal says :kennethvd1997 issued server command: /destination create test.

**Comment by sekwah41** [comment]
Testing with the exact server jar you have and same version of java you have there seems to be no issue at all.

**Comment by sekwah41** [comment]
Could you send the copy of the plugin you have? I downloaded my copy of 0.5.8 from bukkit just to be sure.

**Comment by kennethvd1997** [comment]
[Advanced-Portals-0.5.8-snapshot.zip](https://github.com/sekwah41/Advanced-Portals/files/5117634/Advanced-Portals-0.5.8-snapshot.zip)

**Comment by kennethvd1997** [comment]
the weird thing is I tried replacing the jar file with bukkit.jar and paper.jar and both of them had the same issue even with complete clean server instal and when I replace the jar with an 1.15.2 jar it works just fine.

**Comment by sekwah41** [comment]
Not a single byte different from the ones ive tested. Can you try without any other plugins and see how that runs on your system?

**Comment by kennethvd1997** [comment]
same result

**Comment by sekwah41** [comment]
Try giving this a try as I have compiled it with OpenJDK before (this should have compiled with the normal JDK)
[Advanced-Portals-0.5.8-snapshot.jar.zip](https://github.com/sekwah41/Advanced-Portals/files/5120669/Advanced-Portals-0.5.8-snapshot.jar.zip)

If you are still having issues then I am genuinely stumped then as to what is going on then. It seems like the commands are being read in the plugins.yml but then the code isn't running for some reason and I can't see any reason why that would be if there are no error logs whatsoever. Can you try downloading OpenJDK instead? https://adoptopenjdk.net/ They are more up to date with security patches so its generally a better plan to use than the default.

**Comment by sekwah41** [comment]
At this time we are finding this impossible to replicate. Any further info from others experiencing the same issue would massively help to get to the bottom of this.

**Comment by sekwah41** [comment]
Due to finding this impossible to duplicate again, we are closing the issue.
