### ISSUE TITLE
Do portals work from 1.8 -> 1.16?

### ISSUE THREAD

**Issue by Walnuttt** [sekwah41/Advanced-Portals#219]
Not exactly an issue, but I just want to know whether the plugin can take the player from a 1.8 lobby to a 1.16 world on a BungeeCord network. On the spigot website, it specified that the newer versions don't support versions lower than 1.13 and to use version 0.0.41, but that says it supports from 1.8 only until 1.12.

So is there anyway to do this, or would I have to try find a similar plugin?

**Comment by sekwah41** [comment]
Older versions don't support location specific portals but the bungee tag still works.
