### ISSUE TITLE
Multiple Issues

### ISSUE THREAD

**Issue by BiGUNMAN** [sekwah41/Advanced-Portals#22]
So I just loaded up the plugin, and by reading through the list of commands either the documentation is wrong or the plugin is seriously messed up.

/portal help - Gives me the error message: "You need to type something after /portal If you do not know what you can put or would like some help with the commands please type "/portal help"".

/portal list - Doesn't work (not sure if its suppose to be an option, would be nice to see it added if isn't).

/portal portal - Doesn't give you a portal block.

The following procedure did not work for creating portals either:
/desti create spawn
/portal selector - I select each side.
/portal create name:spawn desti:spawn (I also tried using bungee:hub as another destination).
It successfully creates the portal, or so it says.

The files exist for both the destination and portal, but it doesn't seem to add the destination upon file creation (after multiple different ways of creating/comparing the files).
I even tried manually adding destination to the portals file, and that didn't work out either, complaining the destination doesn't exist (when its in the destination files (case sensitive also)!

Bungeecord also doesn't work using the create command, but when I added it in the configuration manually it actually worked.

I also attempted to manually add tppos instead of a destination and that didn't work either, returning a "destination doesn't exist/config corrupted" (no, the config wasn't corrupted, all YAML order was kept proper).

Thats all I have to say atm. It would be nice to be able to remove the /warp command, as it does mess with other warp plugins.

I used a version downloaded from SpigotMC.

**Comment by sekwah41** [comment]
I will take a look once I have finished my coursework, but atm I feel I need to rewrite the config readers as I origionally coded them when I started making plugins. Also I will take a look at all the errors and try to find why it is being caused.

**Comment by Sikatsu** [comment]
The first 3 issues i have also, but i don't really need them.

The 4th issue is how i made my portals without issues actually :/

**Comment by sekwah41** [comment]
There are a lot of points in here for bugs and all sorts, I will try to find them and fix then once I have more free time to work on personal projects :)

**Comment by Sikatsu** [comment]
Indeed, commands are not working which should be working, /portal list would be nice. Looking forward to updates in the future. ^^

**Comment by sekwah41** [comment]
Are the problems working now? Also I have made a seperate issue as an enhancement for the list commands :)

**Comment by Sikatsu** [comment]
@sekwah41 Atleast the first 3 do still not work :)

**Comment by sekwah41** [comment]
List is not a command, help I just havent completed the menu and portal was broken when 1.8 removed being able to hold the portal block. I will add a method such as placing purple wool that turns into portal blocks.

**Comment by Sikatsu** [comment]
It would be a nice command to see the destination and portal names. I have to make guesses now. Help would be nice aswell, as for the portalblocks I have no idea where that's needed for. :P

**Comment by sekwah41** [comment]
atm you can type /portal select then punch in an area and it tells you what you have selected :) that stops the guessing.

**Comment by Sikatsu** [comment]
Good point, already forgot about that again.

**Comment by sekwah41** [comment]
I will be redesigning the gui's in this next major update. All the command issues should be fixed or what needs to be added should be added soon.

**Comment by sekwah41** [comment]
Should be fixed in the next update
