### ISSUE TITLE
1.16.1 portal not working

### ISSUE THREAD

**Issue by donvdp** [sekwah41/Advanced-Portals#220]
After updating my excisting portals work, but new portals cannot be created. portals.yml file is updated with the newly created portal, but it isnt working. Any idea's on how this is possible?

Trying to create a portal that teleports the players from the lobby to the skyblock server. command im using = /advancedportals create name:Skyblock bungee:skyblock triggerblock:WATER

ingame it tells me, portal created succesfully (see below screenshot)
https://imgur.com/4SLyhuo

config file is edited and the new portals shows up in the config. but when i walk through the portal nothing happens. (see below screenshot)
https://imgur.com/bdi8hkV

running papermc-133 (spigot 1.16.1) and Advanced-Portals-0.5.8-snapshot.jar

**Comment by sekwah41** [comment]
Can you send a screenshot of the portal you have as well as one with debug mode on (f3) standing in the portal where you think it should be triggering?

**Comment by sekwah41** [comment]
This seems to be a bukkit issue with the way blocks were at least being set not properly being updated to plugins.
