### ISSUE TITLE
Portal warp to work the same as a cross server destination portal

### ISSUE THREAD

**Issue by iTz-MrAnonymous** [sekwah41/Advanced-Portals#221]
Hello,

I was just wondering if it would be possible to make it so when the command `/portal warp <portal_name>` is used, that it could function just as it would for portal that has been set up to do a cross server destination. Currently, it will only teleport me to the server and not the destination set on that server as well.

Thanks

**Comment by sekwah41** [comment]
As destinations do not have server tags and are unknown to other servers that's not really possible atm. I may be able to make it so when you trigger it with <portal_name> <bungee_name> it will go the same as entering a portal though. Would that be fine?

**Comment by iTz-MrAnonymous** [comment]
Yeah, that could be great if you could get that to work!

**Comment by sekwah41** [comment]
Ive been quite busy with a deadline this week but I'll see next weekend or if I get some days off to work on personal projects.

**Comment by sekwah41** [comment]
Looking at the current code at least it should do this. I am not sure how long that's been in but it should now at least.
