### ISSUE TITLE
Msg translate please

### ISSUE THREAD

**Issue by Benny0505** [sekwah41/Advanced-Portals#224]
Hello,
Sorry for my english.
would it be possible to translate 1 msg?

There is 10 seconds join cooldown protection left

to

Bitte warte 10 Sekunden zwischen jedem Teleport

Thank you

PS: nice Plugin 👍

**Comment by sekwah41** [comment]
Its already in the recode, we just haven't found time to finish the recode yet. Though more and more people are asking for features in the new one so ill try to put some time aside soon.

**Comment by sekwah41** [comment]
Full text translation is in the officially released version. Sorry that it's probably too late 😅
