### ISSUE TITLE
Spamming command when walking through

### ISSUE THREAD

**Issue by fiftywalrus** [sekwah41/Advanced-Portals#225]
Hello, awesome plugin! I think I am using the plugin in a way it may not be intended, but I am using it as a trigger to run a command, but not to teleport the player anywhere. But when I do  that the command for the portal is triggered many times. Is there a way to have the command run only the first time a player enters the portal block? Or maybe I should just be looking for a different solution?

**Comment by sekwah41** [comment]
Ok so ive found the issue. There is code already in there to stop this but I assume the head of your player or the feet of your players are outside of the portal region or triggerblocks. I will add a fix.

**Comment by sekwah41** [comment]
Here is a new build that should fix all your problems :)
