### ISSUE TITLE
1.16.4 not working

### ISSUE THREAD

**Issue by VexiusNetworkUS** [sekwah41/Advanced-Portals#226]
Portals aren't working in 1.16.4, they say they have enabled but none of the portals work.

**Comment by sekwah41** [comment]
Do the commands still work? If not check my discord https://discord.sekwah.com/

In the advanced portals chat near the top there should be a newer download. There's a weird bug with the public one atm that I think it fixes but I've not been able to confirm it.

**Comment by sekwah41** [comment]
Give this a go https://share.sekwah.com/Advanced-Portals-0.5.10-snapshot.jar

**Comment by sekwah41** [comment]
Due to the inactivity, I will assume its the same issue that overs are having
