### ISSUE TITLE
Right/Left click interaction errors

### ISSUE THREAD

**Issue by OldTownMC** [sekwah41/Advanced-Portals#23]
http://pastebin.com/87pTi1PU

Upon right/left click

**Comment by sekwah41** [comment]
Please try the most recent test build :)

**Comment by sekwah41** [comment]
Please try the most recent test build :)

http://puu.sh/lOZSI/e067f6b9d7.jar

**Comment by OldTownMC** [comment]
I believe its gone, but plugin is still broken as you know.

**Comment by sekwah41** [comment]
Ahh so the other issues, ill try to fix those soon :)
