### ISSUE TITLE
Portals Teleporting People Back To Their Previous Location

### ISSUE THREAD

**Issue by NotGeri** [sekwah41/Advanced-Portals#233]
Heya!👋
There's a glitch where my players would travel to spawn through the nether and when they go through an AP portal, they and up being back at their own nether portals.

Managed to replicate it consistently now. It only happens once for every player after a restart. 

1. Go through a regular nether portal to the nether which is far away from spawn.
2. Go to the main nether portal (which uses AdvancedPortals to link to spawn)
3. Go through and don't rust out of the portal but stay there for a few seconds.
4. Get teleported back to your original, regular portal.

**portals.yml**: https://i.geri.dev/DkzQtB.txt
**destinations.yml:** https://i.geri.dev/Q5mBf3.txt
**config.yml**: https://i.geri.dev/xdf20B.txt

**Versions**: 
- Running Purpur 1.16.5 behind a Waterfall proxy.
- Plugin version 0.5.12 (?- I was a bit confused about this because on Spigot it says the latest version is 0.5.10 but /ver showed this: https://i.geri.dev/5pOPEb.png)

**Video showcasing this issue**: https://streamable.com/6moido (Apologies for the horrible quality)

**Comment by sekwah41** [comment]
Need to look at this this weekend.

**Comment by NotGeri** [comment]
Hello, any updates on this? ^^

**Comment by sekwah41** [comment]
Sorry had a few things I had to deal with first over the weekend. I hope to take a look at this in the next few days :)

**Comment by znopp** [comment]
It's been 2 years, any updates? I want to use this plugin as a portal on the server is too big and leads to the wrong destination, but not if this bug is still present.

**Comment by sekwah41** [comment]
It seems that this bug has only been replicated from what I've seen on paper and forks of paper. Though the whole system kind of needs a revamp. There are some weird cases with portals that were removed and re-defined it seems under a different event. So i need to review the events that happen or what happens during portal travel that it may miss.

Tbh that whole section needs rewriting based off the events as its a little bit of a mess of trying to catch edge cases from old versions.

**Comment by znopp** [comment]
I understand. Would a patch be closer to Soon, or more like Eventually?

**Comment by sekwah41** [comment]
Im away for a week and likely will be busy for a week or two after that but I can take a look after. I need to outline whats causing it again to reproduce so could to provide as much info as possible? E.g. mc version, the fork you are using of spigot, steps to reproduce & how often roughly it seems to occur if its not common.

**Comment by znopp** [comment]
Well, I may have been too quick to blame. It seems to be working perfectly fine in 1.19.2...

Sorry!

**Comment by sekwah41** [comment]
Its allright ^.^ @znopp it has been an issue in the past though it seems to be less common in later versions.

**Comment by NotGeri** [comment]
Great to hear it works in newer versions; closing now.
