### ISSUE TITLE
ServerConnector has connected/disconnected

### ISSUE THREAD

**Issue by CJM821** [sekwah41/Advanced-Portals#234]
I made a portal using this with bungee, but when I try to teleport with it, my server prompts me like it's going to teleport but doesn't.
![image](https://user-images.githubusercontent.com/79784293/109411614-9fd09380-7960-11eb-898e-f5ff7f3501bd.png)

**Comment by CJM821** [comment]
(THIS MIGHT BE AN ISSUE WITH CARDBOARD MOD, NOT PORTALS. I WILL CONTACT HIM INSTEAD)

**Comment by sekwah41** [comment]
We only make a connection request. If the connections themselves don't work it's on the network.
