### ISSUE TITLE
portals

### ISSUE THREAD

**Issue by wolfisnamee** [sekwah41/Advanced-Portals#237]
so i was testing my portals with my friends and one of them werent op and it said "you do not have permission to join" with is the only plug in have on my server is anyone can help that will be great thanks

**Comment by wolfisnamee** [comment]
> a

Sorry for the bad grammar btw I was on my phone

**Comment by sekwah41** [comment]
Is this a bungee server message?

What command did you use to make the portal?

**Comment by wolfisnamee** [comment]
No it is not

/portals create name:pvp

**Comment by wolfisnamee** [comment]
To be honest with you i am fairly new to plug ins and i really dont know what server message all i kbow is its Spigot server if that help in any way

**Comment by sekwah41** [comment]
You need to run the command `/portal create name:pvp bungee:servernametogoto`
