### ISSUE TITLE
Portal teleport into the void?

### ISSUE THREAD

**Issue by SirCraftypants** [sekwah41/Advanced-Portals#238]
Hi,

I have a void world with island builds, some 10 blocks thick below ground level and others upto 40 blocks thick. When i first set the portals up they were working fine, a few weeks later and they're teleporting below the teleport positon, so you are falling into the void, then before you hit the void your re-teleported to the correct spot.

I use Keepchunks for all area's around the portals and their teleport points, my server has a steady tick of 20.

any ideas?

Paper Spigot 1.16.5
Minecraft Client 1.16.5

**Comment by sekwah41** [comment]
There seems to be a common paper I've only seen explicitly on paper to do with players falling into the void.

Are they actually teleporting below the ground or are they just falling? 

You can see where the players are being tried to teleport to based on where it creates the particle effects. If the particle effects are below the ground then there is an issue going on and I can take a look into it. Otherwise, I would recommend possibly contacting paperspigot as this is not logic directly responsible by Advanced Portals.

**Comment by SirCraftypants** [comment]
teleporting just below the teleport position in the ground and falling through it

**Comment by SirCraftypants** [comment]
it's not happening on all my portals though.

Example, i have big sky islands and if the portals are located in the center of the island the portals work fine, but if the portals are located on the edge of the sky island, you fall through.

**Comment by sekwah41** [comment]
We explicitly teleport to the coordinates listed in the portals.yml file. If those are correct then I doubt its something being caused by advanced portals.

**Comment by SirCraftypants** [comment]
ok so i've spoken to the essentials x team, the paper team, no one seem to have a clue.

All my warp area's are keepchunked, but it's like every time i portal warp from one portal to another portal in the same world, i'm just in free fall while watching the chunks load above me in to the distance.

The portals that go from one world to a different world are working fine. it's only same world portals that have the problem.

I've spoken to the server host and they can not find any issues with the server.

**Comment by sekwah41** [comment]
I don't believe keepchunk will effect it at all. From my understanding of the issue, it sounds like even if paper has the chunk loaded if the client doesn't load it fast enough paper doesn't seem to actually verify if the player should be able to make that move properly. I'm likely wrong on this but it's only ever paper I've seen issues of people being able to fall into the void.

Could you possibly try spigot and see if the issue is still there? That would be the easiest way to narrow down if it's spigot or not.

**Comment by SirCraftypants** [comment]
> 
> 
> I don't believe keepchunk will effect it at all. From my understanding of the issue, it sounds like even if paper has the chunk loaded if the client doesn't load it fast enough paper doesn't seem to actually verify if the player should be able to make that move properly. I'm likely wrong on this but it's only ever paper I've seen issues of people being able to fall into the void.
> 
> Could you possibly try spigot and see if the issue is still there? That would be the easiest way to narrow down if it's spigot or not. It's just every time I've seen people swap off paper it seems to fix it.

yeah the problem with that is if i revert to spigot i'm going to lose a lot of performance on my production server.

I reduced the view distance to 10 but it doesn't seem to have done anything, can you think if any settings i may be able to try?

**Comment by sekwah41** [comment]
Im only asking you to test it temporarily, this will confirm if it is an issue that paper needs to look into or something wrong with my plugin.

I can likely add some code which will prevent this when I get some time, however if this is a issue with paper I would personally say its a pretty serious issue.

**Comment by SirCraftypants** [comment]
> 
> 
> Im only asking you to test it temporarily, this will confirm if it is an issue that paper needs to look into or something wrong with my plugin.
> 
> I can likely add some code which will prevent this when I get some time, however if this is a issue with paper I would personally say its a pretty serious issue.

No need, Paper have just confirmed your previous comment 

quote: 

the client basically starts doing its own ticking in the world
and, given it has nothing to stand on falls, as soon as the server tells the client the current state it syncs back up

**Comment by SirCraftypants** [comment]
I've optimized every possible setting but no success so rather than you get anymore questions about this, if i could one suggestion.

That you place somewhere that users have had issues with falling through chunks when both portals are in the same world with a reasonable amount of distance between them, that this is down to a client issue and can not be fixed by using a chunk loader. As far as world to world portals are concerned, they are not affected by this issue. If this information was available to me then i would not have spent two days bothering you and wasting my own time.

**Comment by sekwah41** [comment]
Will be adding the info and flagging this in case its a common issue again.
