### ISSUE TITLE
Normal User can use /desti list without permissions 

### ISSUE THREAD

**Issue by SoraCent** [sekwah41/Advanced-Portals#239]
Good Day,

I have the problem that a normal user without any Advancedportals Permissions can use **/desti list** and sees every Destiations. Normally it should show that the player has no Permissions to list the Destinations shouldn't that be normal?

Does someone also has this problem ?

Thanks for anwsering and helping :D

**Comment by sekwah41** [comment]
I will take a look and remove it. Sometimes I forget to remove these as there is no way to activate them so I tend to forget to block them.

**Comment by sekwah41** [comment]
Permissions have been reworked
