### ISSUE TITLE
Wrong command syntax halts the server.

### ISSUE THREAD

**Issue by martinambrus** [sekwah41/Advanced-Portals#24]
Hi, I just tried to create a portal by using a "command:somecommand" syntax, where I forgot to enclose somecommand in quotes. This has completely slowed down the server until the point it fell over. Furthermore, trying this with quotes, it ignored the closing one and took everything after the closing quote as a command, resulting in this set as a command to execute: "rtp" triggerblock:water (rtp is the actual command)

Update: upon further investigation, the command syntax does not work even when it's the last thing left in the chat line. It still freezes and crashes the server. This is all Spigot 1.8.8

**Comment by sekwah41** [comment]
I will try to replicate this with a build of 1.8.8. I am not sure why this does this :P was it if you forget the second " or both?

**Comment by martinambrus** [comment]
first, I forgot both, then it did the same when both were in and command was the last thing in the chat

**Comment by sekwah41** [comment]
I will check, as far as I remember the code shouldnt have any problems like that but problems like this can be caused by silly little mistakes :P

**Comment by sekwah41** [comment]
I have verified the bug and found the issue, rather than using a += I kept setting the loop back to 1 so it was infinitely looping, for now just dont use the command argument (sorry for the inconvenience. Ill post a working test release link here when possible)

**Comment by sekwah41** [comment]
Fixed (Im pretty sure it is at least...)
