### ISSUE TITLE
please add support for Velocity`s "modern" ip-forwarding option

### ISSUE THREAD

**Issue by ChiAkuma** [sekwah41/Advanced-Portals#241]
The title says it all. Please add support for Velocity`s "modern" ip-forwarding option.
I mean now it only works with the legacy option, but i dont like to let it as legacy for long....
for e.g. security and stability reasons.

So please if you can add that support. ;)

thanks

**Comment by sekwah41** [comment]
There is support that hasnt been fully merged in. I need to look at adding auto detection for that though ;)

Ill see what I can do later or tomorrow :D

**Comment by LaurenceBarnes** [comment]
You can get a working jar already in the discord channel. Ping me there so I can link it to you.

**Comment by sekwah41** [comment]
Fixed in the latest version. Though exploring adding a delay to better support issues with other plugins.
