### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by AggerTV** [sekwah41/Advanced-Portals#249]
How do I disable the particles being played when entering a portal?

**Comment by AggerTV** [comment]
I also wan't to disable the actionbar message

**Comment by sekwah41** [comment]
Have you tried disabling the options in the config then reloading the plugins. `/portal reload` only reloads the current portals and not the configs.

**Comment by AggerTV** [comment]
I'm sorry if it's really obvious, but what's the setting called for disabling the actionbar message?

**Comment by sekwah41** [comment]
WarpMessageDisplay
