### ISSUE TITLE
Custom warp messages

### ISSUE THREAD

**Issue by sekwah41** [sekwah41/Advanced-Portals#25]
Add @player and @desti tags for more customization as well as color codes.

E.g. message:"Welcome to @desti"

Also maybe replace underscores with spaces.

**Comment by iLaloxYT** [comment]
In what version of the plugin this was added, I wanna use it in my 1.7.10 server

**Comment by sekwah41** [comment]
this is not added yet, the issue will be closed when it does

**Comment by iLaloxYT** [comment]
Oh thanks! And it will work with Minecraft 1.7.10? :)

**Comment by sekwah41** [comment]
I don't think that is listed on the supported versions. Sorry.

I forget what changed but it was quite big in comparison to 1.8 and up

**Comment by sekwah41** [comment]
Didnt mean to close xD

**Comment by iLaloxYT** [comment]
So sad, I need to use Cauldron 1.7.10 :(

**Comment by sekwah41** [comment]
I can take a look and see whats stopping me, I think it was quite an annoying api change...

**Comment by sekwah41** [comment]
Will be added in the recode though at the moment its not per portal (will add)
