### ISSUE TITLE
Implement a capitalize method inside Lang

### ISSUE THREAD

**Issue by Kariaro** [sekwah41/Advanced-Portals#252]
https://github.com/sekwah41/Advanced-Portals/blob/39dd1fb623aa6b8bb5eebfe2546b80cbfac7e7dc/src/main/java/com/sekwah/advancedportals/core/commands/CommandWithSubCommands.java#L63

In the code above using a clear typed method call like `Lang.capitalize(commandExecuted)` would improve the readability of the code and make it look better.

Is this a valid issue?

*I want to make sure I understand how to make issues and/or feature requests.*

**Comment by sekwah41** [comment]
I'll have to check what this does exactly though it would count as an enhancement.

Personally I don't like the idea of forced capitalisation as most commands are written without caps.
