### ISSUE TITLE
cooldown?

### ISSUE THREAD

**Issue by AggerTV** [sekwah41/Advanced-Portals#254]
Hello, I'm sorry if I'm just blind, but how do I add a delay for going through a portal?

**Comment by sekwah41** [comment]
you cant set a delay value, though you can set it so it'll wait for the portal trigger event (though that requires you to not be in creative)

there should be a `delay:` or `delayed:` tag you can set to `true`

**Comment by AggerTV** [comment]
I want it to be for survival players as well

tor. 3. jun. 2021 kl. 14.40 skrev Sekwah ***@***.***>:

**Comment by sekwah41** [comment]
I mean you need to be in survival for it to have a delay. Creative mode instantly activates nether portals. The trigger block also needs to be nether as we use the default trigger events.

**Comment by AggerTV** [comment]
This is my config, I can't seem to find the option
`# Advanced Portals Config
# 
# To set this file back to its default state just delete it and reload the server or restart it!
# 
# Will update whenever there is a config update from an older version so may not be the latest plugin version
ConfigVersion: 0.5.10
UseOnlyServerMadeAxe: false
AxeItemId: IRON_AXE
CanBuildPortalBlock: true
PortalProtection: false
PortalProtectionArea: 5
DefaultPortalTriggerBlock: PORTAL
StopWaterFlow: true
ShowSelectionBlockID: RED_STAINED_GLASS
WarpParticles: -1
WarpSound: 1
ShowBungeeWarpMessage: false
ShowSelectionShowDuration: 10
WarpMessageDisplay: -1
UseWarpPrefix: false
UseCustomPrefix: false
CustomPrefix: '&a[&eAdvancedPortals&a]'
CustomPrefixFail: '&c[&7AdvancedPortals&c]'
BlockSpectatorMode: false
PortalCooldown: 5
ThrowbackAmount: 0.7
DisableGatewayBeam: true
CommandLevels: opcb
CommandLogs: true
`

**Comment by sekwah41** [comment]
Its per portal. Its a tag not a config option.
