### ISSUE TITLE
/ap reload does not reload config.yml

### ISSUE THREAD

**Issue by jonaskohl** [sekwah41/Advanced-Portals#255]
When issuing `/ap reload`, it says `[AdvancedPortals] Reloaded values!` but it doesn't reload changes from `config.yml`.

**Comment by sekwah41** [comment]
The recode should fix this to this though due to progress made recently with it I won't be making a quick fix for the old version for now.

**Comment by sekwah41** [comment]
Most config values are now reloaded.
