### ISSUE TITLE
bukkitpage shows up in tab completor, but is not registered as a sub command. - minor bugg

### ISSUE THREAD

**Issue by Tirco** [sekwah41/Advanced-Portals#257]
the command **/portal bukkitpage** shows up in the TabCompletor, but when you run it, it gives you the default "You need to type something after /portal" message.

**Comment by sekwah41** [comment]
Ah thanks for pointing this out. Ill add it when I get a bit of time later.

**Comment by sekwah41** [comment]
Forgot to tag this in the issue but this is now released in 0.7.0 (once it updated on curseforge)
