### ISSUE TITLE
Permission for /destination create does not work

### ISSUE THREAD

**Issue by ShadK** [sekwah41/Advanced-Portals#29]
Hi,

When I add the permission "advancedportals.createportal" to my group, I can make a portal without any problem, but I can't do the command /destination create, it says that I don't have the permission to create portals, it is as if the permission for /destination is not the same as /portal, unlike what the wiki says, cause when I OP myself I can do the command /destination

**Comment by sekwah41** [comment]
Ill check the code, I may have missspelt the permission

**Comment by sekwah41** [comment]
My mistake, I put it as AdvancedPortals. Please try it as caps and ill update it next release :)

**Comment by ShadK** [comment]
Hi, it still doesn't work, but I think the reason is that my permission plugin (zPermissions) does not support caps

**Comment by sekwah41** [comment]
This weekend ill build a new copy if I remember, I have mocks this week so I cant right now

**Comment by sekwah41** [comment]
Try this, I made a quick build :) http://puu.sh/nC9wG/01f28fb1b9.jar

**Comment by ShadK** [comment]
Hi,

I tested your build, and permission for /destination create still doesn't work.

**Comment by sekwah41** [comment]
http://puu.sh/nERx8/f30dbf6507.jar try this, ive defined the permission in the plugin.yml and also changed it to advancedportals.desti.create

**Comment by ShadK** [comment]
It works, thank you !

**Comment by sekwah41** [comment]
Glad I could help ^.^
