### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by Loqed44** [sekwah41/Advanced-Portals#290]
Hello plugin maker!

I have a good idea what everyone would like! that you can add a command to the portal like /rtp that if people go in the portal that this command will be used. now you have to set a destination but you can add like command /warp shop, /spawn or /rtp. With commands you could make it much better for everyone! Thanks for viewing!

Mvg. Loqed44

**Comment by sekwah41** [comment]
You can already do this unless I am misunderstanding you.

You just need to make sure you have a plugin that adds that command and use the command:"some command here" tag e.g. command:"rtp"
