### ISSUE TITLE
portal permission

### ISSUE THREAD

**Issue by seema84** [sekwah41/Advanced-Portals#295]
Does the perm "portals.portalname" still work to authorize individual portals? 
Is there any documentation for this? I could not find anything current on this.

Version: 0.7.0

**Comment by sekwah41** [comment]
Weve never used those permissions. If you want to set a portal to need a permission use `permission:some.permission.here` and it will check if the player has whatever is after `permission:`

**Comment by seema84** [comment]
Oh that's right. I had set the perm tag like this.

Is there any way to stop the teleport of the vanilla nether portals?

**Comment by sekwah41** [comment]
You would need to do it using multiverse or disable the nether. By default we disable portals in overlapping regions.

**Comment by seema84** [comment]
I use multiverse (and have disabled the nether) but there is a issue.

https://github.com/Multiverse/Multiverse-Core/issues/2634
