### ISSUE TITLE
How to give permission for a specific desti

### ISSUE THREAD

**Issue by Nebulizer1213** [sekwah41/Advanced-Portals#298]
I want to allow people to do desti warp hub. I used the permission advancedportals.warp.hub but it did not work. What is the correct perm to do this?

**Comment by sekwah41** [comment]
What is the command you have used to create the portal? By default, everyone has access to all portals.

**Comment by Nebulizer1213** [comment]
I think I used the normal portal create command. I don't really remember.
these are my config files

[config.yml](https://github.com/sekwah41/Advanced-Portals/files/7573917/config.txt)
[portals.yml](https://github.com/sekwah41/Advanced-Portals/files/7573918/portals.txt)
[destinations.yml](https://github.com/sekwah41/Advanced-Portals/files/7573919/destinations.txt)

**Comment by sekwah41** [comment]
So you want people to be able to type the command `/desti warp hub`? if so you need `advancedportals.warp.hub` or `advancedportals.warp.*` as well as `advancedportals.desti` to give access to using the  `/desti` command in the first place.

**Comment by Nebulizer1213** [comment]
The problem is that they did not have advancedportals.desti thanks for the help
