### ISSUE TITLE
How can I remove missing warp message?

### ISSUE THREAD

**Issue by Strahilchu** [sekwah41/Advanced-Portals#304]
[17:28:40 ERROR]: [AdvancedPortals] The destination 'survival' has just had a warp attempt and either the data is corrupt or that destination doesn't exist!

I just want portal to take players to that server where they last left off and not to a warp, but when it didn't let me make a portal without setting a warp when I tried. So I just added a warp to the portal but never actually set a warp in the server it goes to. Works as I want it but I get this message every time.

**Comment by sekwah41** [comment]
You don't have to set a destination when making a bungee portal. Just use the bungee tag and leave out the desti: tag.
