### ISSUE TITLE
Portal creation returns message that the points need to be in the same world

### ISSUE THREAD

**Issue by JasonRaveling** [sekwah41/Advanced-Portals#311]
I'm not sure why I'm getting caught in the conditional for checking that points are in the same world ([AdvancedPortalsCommand.java line 522](https://github.com/sekwah41/Advanced-Portals/blob/75d2be30fe4dfe702216cbb5941dac1afeb79959/src/main/java/com/sekwah/advancedportals/bukkit/AdvancedPortalsCommand.java#L522)).

I am using the selector to set point pos1 and pos2 a few blocks from each other. But when I run the command `/potal create name:test desti:myspawn` I get the message "The points you have selected need to be in the same world!"

I am on a Spigot server running on Minecraft 1.18.1 with Advanced Portals 0.9.0. I also have WorldGuard and WorldEdit running. I am not sure how to debug in Minecraft otherwise I'd try to get more info. If there is any other info that would be helpful, please let me know.

**Comment by sekwah41** [comment]
This has been fixed in 0.9.0
