### ISSUE TITLE
Can't create portal for some reason! V0.9.0

### ISSUE THREAD

**Issue by Strahilchu** [sekwah41/Advanced-Portals#312]
After updating to the latest version I run /portal create name:hardcore bungee:hardcore triggerblock:air

This is the message I get, screenshot shows it and I'm basically selecting the barrier blocks where the text is, worked for my other portals so I am confused

![2021-12-21_08 20 50](https://user-images.githubusercontent.com/69178324/146945290-d92872e8-718f-46fb-9d13-95cf940a4724.png)

**Comment by Strahilchu** [comment]
Never mind I set triggerblock:AIR instead of lower case "air" and it randomly worked

**Comment by sekwah41** [comment]
@Strahilchu upgrade from 0.9.0 as there is an issue with creating a portal anyway. 0.9.1 fixes the problems.
