### ISSUE TITLE
Not working with commands from other plugins such as RandomTP

### ISSUE THREAD

**Issue by Creeper-Kingz** [sekwah41/Advanced-Portals#317]
Unfortunately this doesn't seem to be working with RandomTP command here - https://www.spigotmc.org/resources/%E2%9C%85-randomteleport-%E2%9C%85-1-17-1-18-1.20063/

Not sure what the issue is exactly but can't seem to set the command to work without a destination and still have it work. The layout of the command is as follows: /portal create name:portal1 triggerblock:air command:"#randomtp @player"

Any help is appreciated thanks :)

**Comment by sekwah41** [comment]
Please check the logs to see what command it runs and the feedback it gives.

**Comment by Creeper-Kingz** [comment]
I managed to get it to work after playing around with the config for the
RTP plugin. Wasn't the fault of your plugin but rather the other plugin.
Great work on the plugin btw. Love it

**Comment by sekwah41** [comment]
Thanks 😊
