### ISSUE TITLE
Cant Delete Destinations Once Created

### ISSUE THREAD

**Issue by Bowbuck2** [sekwah41/Advanced-Portals#32]
When i do /desti Remove {Name} It Says: No Destination By that name exists

**Comment by Bowbuck2** [comment]
Also Found This Issue: Says Internal Server Error When trying to create a portal 

http://pastie.org/10815704

**Comment by Bowbuck2** [comment]
On 1.7.10

**Comment by sekwah41** [comment]
I can take a look but 1.7.10 is no longer supported with new versions at least :(

**Comment by sekwah41** [comment]
Which version are you using? There used to be bugs for one at least with portal creation.

**Comment by Bowbuck2** [comment]
I just did a World Reset And Updated all of my plugins but it seems to be working Now, Very Strange Sorry To bother you

**Comment by sekwah41** [comment]
Its ok xD Glad its fixed :)
