### ISSUE TITLE
/portal wand is not listed in the in-game help menu

### ISSUE THREAD

**Issue by Fairweather-Furry** [sekwah41/Advanced-Portals#333]
It might seem a bit redundant, but the command '/portal wand' doesn't appear in the '/portal help' list of commands, which seems to be a bit of confusion for anyone using the plugin who's new to the plugin or isn't using WorldEdit. I'd think adding it would make the plugin a bit more user-friendly. The command is mentioned in the Wiki on the main page and WorldEdit Integration page, but only briefly.

**Comment by sekwah41** [comment]
It's an alias for `/portal selector` though I'll take a look when I'm back from my trips at what is currently there.

**Comment by kylehen9758** [comment]
/portal selector is in the help list, so maybe a good way to do it is maybe list them together? I.E. "/portal selector AND /portal wand - Gives you a region selection wand"

**Comment by sekwah41** [comment]
Probably easier to leave separate otherwise that's quite a long line when some people have weirdly large chat text
