### ISSUE TITLE
Portal Selector won't turn off

### ISSUE THREAD

**Issue by hyzercal** [sekwah41/Advanced-Portals#339]
My iron axe seems to be a selector/wand permanently. How do I turn this off.

**Comment by sekwah41** [comment]
There is no toggle fo that though you can enable in the config to only use server-created axes as wands.

**Comment by hyzercal** [comment]
Ok thank you. I will look into that.

**Comment by sekwah41** [comment]
It should be the setting UseOnlyServerMadeAxe in the config file
