### ISSUE TITLE
Provide Pom file for compilation with mvn

### ISSUE THREAD

**Issue by mcCURS0R** [sekwah41/Advanced-Portals#34]
I've tried to create a Pom file but Java and Maven is not my beach has i'm mainly a c# dev.
The problem is that i need to get all the dependencies...

`src/com/sekwah/advancedportals/compat/bukkit/v1_10_R1.java:[3,37] package net.minecraft.server.v1_10_R1 does not exist`

I think i'm missing craftbukkit. i have this in my pom:

`<dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot-api</artifactId>
            <version>1.10-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
        
   <dependency>
        <groupId>org.bukkit</groupId>
        <artifactId>bukkit</artifactId>
        <version>1.10-R0.1-SNAPSHOT</version>
        <scope>provided</scope>
 </dependency>
`

**Comment by mcCURS0R** [comment]
Ok, i had to include spigot itself as a system dependency.

**Comment by mcCURS0R** [comment]
1.10 coolness. the problem is that i has via ssh and made de pom by hand :cocktail: 

If you want i can submit the pom i've made. just have to get it from the server :)

**Comment by sekwah41** [comment]
Could you explain what the poms and stuff are? I have never been sure about them and and builds. Im self taught and litteraly only know what ive figured out by toying with and decompiling mc then playing with what ive learnt :P

I have a lot of general programming conventions to learn xD

Also what was wrong? After exams ill build it for 1.10 its just atm my laptop can only do java 8 and 6. That or ill install java 7 to make a new build and publish it.

If you need a quick fix delete the compat files and only leave the version of spigot you need.

**Comment by sekwah41** [comment]
Ohh I noticed you said you werent brillaint either :P well yea im not too sure how to link these as you need to build each one individually. Ill have to take a look at maven when I have time. Its really good for public projects it seems :)

**Comment by sekwah41** [comment]
Task for self: Learn how the hell to use mvn...

**Comment by sekwah41** [comment]
Atm im just building all the jar files and throwing them on the library imports :P

**Comment by mcCURS0R** [comment]
Yes i've built just for the version i need :) i didn't knew about mvn... had to take a crash course :)

**Comment by sekwah41** [comment]
Yea sorry about that. Seeing as ive beem the only developer directly on it and generally work alone in java ive never had the need for it :p probably good to learn either way :)

**Comment by mcCURS0R** [comment]
You are doing a great job! Thanks for a fantastic plugin! :)

**Comment by sekwah41** [comment]
If you are using java 8 I could jave just send you a build from my laptop :P or did you want to do more than just build it?

**Comment by mcCURS0R** [comment]
I've built it 2 hours ago :) with sucess

**Comment by sekwah41** [comment]
Also thanks. I have a large recode planned out tjat I need to code now to open it up to other devs to link into servers better and make addons pretty useful and easy to make. E.g. A tag registry system.

Should make it easier for me to add base features easier and better than before too way :) That and stuff that isnt NEEDED or common e.g. vault support can be provided as addons.

**Comment by sekwah41** [comment]
Despite your issue being solved ill leave this open to remind myself to look at mvn for others to set up easier.

**Comment by sekwah41** [comment]
I will be sure to add one once I figure out maven or require one. Atm im not sure how to supply links for bukkit builds :P If there are any other projects i can use as a reference that would be great but for now ill close this and keep an eye out.
