### ISSUE TITLE
Velocity support does not work.

### ISSUE THREAD

**Issue by Virologicbody** [sekwah41/Advanced-Portals#342]
Using Velocity: I have port forwarding set up correctly.

Message in server console:
[AdvancedPortals] Proxy features disabled for Advanced Portals as bungee isn't enabled on the server (spigot.yml) or if you are using Paper settings.velocity-support.enabled may not be enabled (paper.yml)

Paper 1.19.2-271
AdvancedPortals v0.9.2

When trying to use a portal cross-server, message in server console:
[AdvancedPortals] You do not have bungee setup correctly. Cross server destinations won't work.

**Comment by sekwah41** [comment]
You have not enabled the settings it mentions. I believe paper has changed the location of that setting into the config folder under paper-global.yml

**Comment by Virologicbody** [comment]
I have enabled Velocity in /config/paper-global.yml

**Comment by sekwah41** [comment]
Ah yes, just checking  it seems to be they have changed the location name slightly in the config.

For now you can set ForceEnableProxySupport if you want which will enable the features and ill take a look when I get a moment at re-naming the variable so it pulls from the new location.

**Comment by Virologicbody** [comment]
Hi, thank you for the reply.

'Don't worry about enabling that setting'? - ForceEnableProxySupport?
I enabled that and everything is working for me.

**Comment by sekwah41** [comment]
Yep thats the setting :) Its just off by default usually to save people who havent setup their servers correctly which youve shown me you have. Ill update the plugin to support the new setting location.

**Comment by Virologicbody** [comment]
Would you mind if I ask a question? I know this is supposed to be for new features/bug reports but I don't see anywhere to ask... the Spigot discussion seem to be quiet!

When we set a portal how does the plugin move a player from one server to the next? Is there a command the plugin runs?

Thank you

**Comment by sekwah41** [comment]
The plugin sends a packet to the proxy, it's defined in the bungee spec but most proxy's support it.
