### ISSUE TITLE
Can't return top lobby server

### ISSUE THREAD

**Issue by gwgw99** [sekwah41/Advanced-Portals#35]
I created a portal to my creative server, and it actually worked. However, when I use /server lobby to return to the lobby, I return to the lobby server, but im still in the portal. Now when I move, I get sent back to creative.

**Comment by sekwah41** [comment]
Thats due to bungee moving you. You need to move the player when they rejoin if they do that atm sadly. I need to add some new code for that or add a joining server cooldown for portals.

**Comment by sekwah41** [comment]
Should be fixed in the next update
