### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by Maxqia** [sekwah41/Advanced-Portals#36]
What are your reasons for not choosing the GPL? Have you looked at the AGPL?

**Comment by sekwah41** [comment]
Ill take a look. I'm just unsure what each of them were :)

**Comment by sekwah41** [comment]
One thing i was unsure about is with GPL, how much do they need to change it before they can redistribute it? Or would it not allow me to stop people stealing and reuploading my plugin to sites? (issue was in the past i had it taken and put as a paid resource on spigot)

**Comment by sekwah41** [comment]
I may put a GPL license on in the next few days. One thing thats happened is people have made private builds of it. Does that mean they have to show the source code or is it only if its being distributed by them? (im bad with licenses)

**Comment by sekwah41** [comment]
Also nice changes. I still need to rewrite some of those parts but i didn't even notice the listeners dupe xD

**Comment by Maxqia** [comment]
Thanks, I'm still working on it and I'll send you a pull request when I'm done.
Anyways, I am not a lawyer, but from what I understand,
The GPLv3 makes it so
1. You may do anything you want as long without conditions as long as you don't distribute it.
2. You may copy and send the source code without modifying it, but with an obvious copyright notice.
3. If you distribute a modified work, you must also state you modified it, and license your work under the GPL.
4. You must keep intact any notices that state this license applies to the code.
5. You may provide compiled plugins under the same terms of the last 3 items, as long as you also provide the source code.
6. You may link with the AGPLv3 (makes it not infringe on bukkit's license)

The AGPLv3 is the GPLv3 with an additional clause that if you modify it, you must provide all users interacting with it over a network an opportunity to download the source code, and 
you can combine/link it with GPLv3 works.

The GPL says that you can send copies for any charge :(  , but I think that the above terms makes it very hard to do that.

**Comment by sekwah41** [comment]
Ill keep looking around. For now im fine with people modifying it how they want and redistributing it as long as its not being paid for. If you are using it for a network and the network is making money that is fine but not selling it as a plugin to servers. I personally wont do anything to anyone, its just atm I dont want to lose the right to do that with the licensing. (don't wanna feel powerless).

Also in terms of the cooldowns and stuff ive been rewriting some of my own stuff of that and it should appear in the portals rewrite soon. I've been writing and the designing the main parts of it however I still need to add the tag handlers  and tags to the activated portals and remake the GUI's.

**Comment by Maxqia** [comment]
Have you looked at the Creative Commons licenses?

**Comment by sekwah41** [comment]
Will do now

**Comment by sekwah41** [comment]
GNU GPLv3 has now been added as the projects license

**Comment by sekwah41** [comment]
The GPL says they must also refer back to the original luckily. If they haven't made significant changes then anyone smart looking at any redistribution will see its not worth it if there are little to no changes.

**Comment by Foorack** [comment]
@sekwah41 As the LICENSE is added, can this be closed then?

**Comment by sekwah41** [comment]
Done
