### ISSUE TITLE
Portals will NOT work in my velocity server

### ISSUE THREAD

**Issue by HaileyCat** [sekwah41/Advanced-Portals#362]
Portals will NOT work in my velocity server in the way I want them to work. I don't want portals from one spot in a world to another but portals from one velocity enabled server to another and it will not function and I have looked everywhere for a solution that I could find. I have other plugins and they all work flawlessly but I had to get a plugin for going from server to server and it wont work other than teleporting around a single world. 

Advanced portals is installed in every plugin folder, I have full permission and don't want permissions set on my portals so that has not been an issue. test portals work around a single worked but not to other servers. Every server works and had Ip forwarding done correctly as it says to do on the velocity documentation.  I am just so confused as to what and if I am doing something wrong because I cannot seem to find anything saying it should not work. please help

**Comment by HaileyCat** [comment]
advanced portals vbersion 0.9.3
minecraft Velocity 3.2.0-snapshot as on the website for 1.19.4 
PaperMC Server for 1.19.4

**Comment by rautamiekka** [comment]
All PaperMC projects also list the build number.

**Comment by HaileyCat** [comment]
PaperMC version 1.14.4 build 511

**Comment by HaileyCat** [comment]
PaperMC version 1.14.4 build 511

**Comment by HaileyCat** [comment]
> All PaperMC projects also list the build number.

PaperMC version 1.14.4 build 511

**Comment by sekwah41** [comment]
Would you mind sharing the portals.yml file with me on discord? or at least copy the data relating to the portal that isnt working?

**Comment by HaileyCat** [comment]
> Would you mind sharing the portals.yml file with me on discord? or at least copy the data relating to the portal that isnt working?

Its the whole plugin not working between servers but I could do that. also as far as I can tell its multiple files and there's no Central location for any of the files so i do not know what to specifically send if I did.. I have the plugin in the plugins folder for every server and Velocity as well and it worked in a single world but not from one server to another.

**Comment by sekwah41** [comment]
The transfer itself between servers is handled by the bungee standard of sending a packet over a specific channel, you don't need it on the velocity server for a solely bungee portal. As long as you don't have a destination it should just send that packet.

These packets get sent if you have modern forwarding on or not. It's the destination-specific ones that get sent.

I believe they may be case-sensitive. Im not sure. Though if the name matches the destination server it should be able to send you perfectly fine.

The annoying thing is ive seen someone have this issue before though I don't know if they set up something wrong or what because they never told me if they fixed it.

I use a testing velocity setup usually to make sure they all work fine.

**Comment by sekwah41** [comment]
Usually for testing I use two paper servers with a velocity server in the middle. I can happily send you any files you need from a working setup, Feel free to message me on Discord and ill be able to respond faster. Either  in dm's or on my public discord.

I'll make a summary here if you do for others.

**Comment by HaileyCat** [comment]
I will send whatever I need to I just want to be sure I am not wasting your time with sending the wrong thing or that I am just being dumb. I feel I may just be doing something wrong but I don't know and  other than finding another plugin I decided to reach out after trying my best on my own.

Feel free to let me know the best way to reach out on discord rather than here. I am not used to reaching out on here since I know usually its me messing up or not understanding something. I can also give you my discord if you prefer I just don't know if in this chat is the best idea.

So all the servers are PaperMC servers running offline with velocity joining them all as if it is one server and right now i use /server to travel but id rather portals since bedrock support through geyserMC is also installed and its harder to do /server. so there are like 8 servers since its a pc I don' use for anything else.

**Comment by HaileyCat** [comment]
So I spent hours (Genuinly more than 4 hours) trying to properly make a portal and looking things up but it did not work. everything was basicity copy paste or taking already typed commands and changing /portal create and /portal remove only to be sure it was all the same. but this time it worked and i do not know why. if you want any info let me know as i need to now figure out what was different this time since i do not know.

**Comment by HaileyCat** [comment]
so i do not think destinations stay capitalized when you set them up or at least not for me in every circumstance or something because the destination did not work but going to the world did.

**Comment by HaileyCat** [comment]
its not working again or im doing something really wrong

**Comment by sekwah41** [comment]
Its extremely late here, though im available on discord as Sekwah#0001 or you can join my discord server https://discord.sekwah.com/

**Comment by sekwah41** [comment]
Wait a second, what kind of portals are you trying to make? We literally had someone today using bedrock trying to make gateway portals, but because they are solid on bedrock you cant walk inside them so they will never trigger.

If you want gateway portals that support bedrock you need to set the triggerblock to air and make the selection the area around it. Itll trigger before you are inside it but its a small price to pay.

**Comment by HaileyCat** [comment]
I sent a friend request as it said you only accept messages from friends. name HaileyCat on discord

I am using Minecraft Java on a java server using what I mentioned before and I cannot get it to work. I have GeyserMC as a plugin but so far its never conflicted with anything I have seen. I am using java MC on a java server and having issues other than that one random occurrence. if you need to wait till the next day as it is late no worries

**Comment by sekwah41** [comment]
Seems there may have been a typo in the destination or bungee server names.
