### ISSUE TITLE
Portal without destination

### ISSUE THREAD

**Issue by zenandreas** [sekwah41/Advanced-Portals#37]
Hi,

I'm more interested in creating a portal without a destination and only to run a command once a player enters it ( i'm not using it just for this feature and i still want to use the plugin for this as well ).

Apparently i can't create a portal without destination and even if the command should tp the player, the portal gets prioritized and sends him to the configured destination of the portal.

Is there anyway to bypass that?

Thanks

**Comment by sekwah41** [comment]
Ill check. The portal should be able to be created without a destination. Maybe I've changed something by mistake...

**Comment by sekwah41** [comment]
No it works :P for example the command (/portal create name:Testing command:"/kick @player" triggerBlock:AIR) will create a portal that kicks the player if the user has permission.
