### ISSUE TITLE
velocity-plugin.json missing Author. fix's compatibility with autoplug

### ISSUE THREAD

**Issue by mineblow** [sekwah41/Advanced-Portals#374]
I use an auto-update plugin, and for it to work it needs an author specified. It keeps putting out an error because on velocity because of "No Author Found". I have attached a screenshot below showing what it looks like. I hope you could just put author there. there was a pull request #335 to fix this issue which was merge but must have been removed again.  also is a duplicate of #326 and #334
![163696181-f396df08-1d69-4c36-8c80-4aa06833542d](https://github.com/sekwah41/Advanced-Portals/assets/28937464/cbb7cd4d-bf1e-40b3-a3bf-dcc3e50d7eab)

**Comment by sekwah41** [comment]
I don't believe I removed it; ill have to check whats happened there though I am away on business for a while. I might not have the time but ill see.

**Comment by TreemanKing** [comment]
This can be closed now @sekwah41
