### ISSUE TITLE
[suggestion] folia support

### ISSUE THREAD

**Issue by cgw2023** [sekwah41/Advanced-Portals#375]
Please make Advanced Portals support folia platform 1.20.1
It is the newest papermc offical fork https://github.com/PaperMC/Folia
It is getting popular nowadays
Thank you so much!

**Comment by sekwah41** [comment]
Wont be a high priority but I can explore it with the recode. Though my priority is getting the base features through first.

Is it not working with Folia or is it more optimising it for better performance?

**Comment by cgw2023** [comment]
> Wont be a high priority but I can explore it with the recode. Though my priority is getting the base features through first.
> 
> Is it not working with Folia or is it more optimising it for better performance?

Plugin cannot be enabled in folia platform
Folia is different from spigot/paper, it have alot of changes for multithreading, it is made by papermc team. 

https://github.com/PaperMC/Folia

Folia is getting popular now


![image](https://github.com/sekwah41/Advanced-Portals/assets/136877036/b2998b74-30cc-46d0-848e-141fea7d22bd)

**Comment by sekwah41** [comment]
Can you please try using the latest version of advanced portals? by the looks of it you are using a very old version.

0.9.+ would give me more feedback :)

**Comment by cgw2023** [comment]
> Can you please try using the latest version of advanced portals? by the looks of it you are using a very old version.
> 
> 0.9.+ would give me more feedback :)

oh sorry i pressed the wrong version on modrinth

this is version 0.9.2 with error

![image](https://github.com/sekwah41/Advanced-Portals/assets/136877036/6c3f6a17-0bfb-4220-99ac-fa0b3697e5ce)

logs:
https://mclo.gs/wf14aD4


Please help

**Comment by sekwah41** [comment]
Ive had to prioritise other projects rn but im part way through a re-code of advanced portals, I can take a look to see why these dont work during that. Though if I get some time on the weekend I can try to pull it down and gauge how much work it would be to add this.

**Comment by sekwah41** [comment]
Also given the error, there is a risk that it is Folia that is actually erroring, otherwise, the advanced portals Listeners class would be at the top of the stack trace.

Though it could be because I trigger it too early depending on whats going on, so ill have to experiment and see if its just a weird quirk of how Folia works, if it's broken on their end or if its something I can fix.

**Comment by sekwah41** [comment]
I've added Folia support, at least a rough draft. Currently, Folia doesn't seem to properly Implement some of the nether portal events so avoid making nether portal portals until they have done that (even if you are on portal cooldown it'll still trigger as it doesn't fire at all).

It may require more events though folia should really make it support the current ones properly.

**Comment by sekwah41** [comment]
Will be in next release likely tomorrow.

**Comment by sekwah41** [comment]
Check out this if you want 
[Advanced Portals Folia.zip](https://github.com/sekwah41/Advanced-Portals/files/12075068/Advanced.Portals.Folia.zip)

**Comment by sekwah41** [comment]
I may re-consider adding Folia support as it forces such a new Java requirement blocking off any earlier paper versions than 1.17. However, most of the userbase is on 1.16+ at least.

**Comment by sekwah41** [comment]
Though with the recode I am mostly planning to support the latest versions with priority so that is fine likely going forward.
