### ISSUE TITLE
Commands not working at all

### ISSUE THREAD

**Issue by 128912891289** [sekwah41/Advanced-Portals#377]
**Paper version**: git-Paper-"483368e" (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 483368e on ver/1.19.4)
**Advanced Portals version**: 0.9.3
**Logs**: https://pastebin.com/LjFvqKx3
**Config**: https://pastebin.com/2fUUbDvJ
**Issue**: The issue that I was having was that I can't use any Advanced Portals command. The example I've put with logs from running the command as an op (and directly in console), but this also happens with regular users that have just been given admin permissions. This wouldn't be much of a problem but I seem to also now be having issues creating portals from the portals.yml file directly. Let me know if you need any other information.

**Comment by sekwah41** [comment]
I will likely have time this weekend to investigate this. I assume you are also the user who was having issues on discord? Sorry I’ve been very busy with work lately.

**Comment by 128912891289** [comment]
Thanks for the quick reply. I haven't said anything on Discord about this issue.

**Comment by sekwah41** [comment]
For some reason in those logs you are running commands as the server

```
[20:26:11] [Server thread/INFO]: ZappyMonstaa954 issued server command: /advancedportals
[20:26:13] [Server thread/INFO]: ZappyMonstaa954 issued server command: /advancedportals wand
[20:26:14] [Server thread/INFO]: ZappyMonstaa954 issued server command: /ap
[20:26:17] [Server thread/INFO]: [AdvancedPortals] You cannot use commands with the console.
[20:26:23] [Server thread/INFO]: [AdvancedPortals] You cannot use commands with the console.
```

You need to run them as the user in game.

Please check there isn't a plugin clash altering how your commands run.

**Comment by sekwah41** [comment]
Closed for now as I have assumed there is some form of plugin clash or other way it was being ran

**Comment by 128912891289** [comment]
`[20:26:11] [Server thread/INFO]: ZappyMonstaa954 issued server command: /advancedportals
[20:26:13] [Server thread/INFO]: ZappyMonstaa954 issued server command: /advancedportals wand
[20:26:14] [Server thread/INFO]: ZappyMonstaa954 issued server command: /ap`
This is me running a few of the commands in game. I can confirm there is not plugin clash.

**Comment by sekwah41** [comment]
You HAVE to be a player to trigger the commands, and I test on paper usually.

https://github.com/sekwah41/Advanced-Portals/blob/2c919bff062e16addb1cabda927263aa997a9
[Name print test.zip](https://github.com/sekwah41/Advanced-Portals/files/12138971/Name.print.test.zip)
b8a/src/main/java/com/sekwah/advancedportals/bukkit/AdvancedPortalsCommand.java#L57-L60

Can you please give this jar a go and give me the log? It will let me see what it thinks is calling the command at least and see if there is an issue.

**Comment by 128912891289** [comment]
Here is the log from running what you sent me: https://pastebin.com/4BzFq1PQ 
I am using Paper. Thanks for your help.

**Comment by sekwah41** [comment]
What is it responding to a player now when you type the command? I cant see any logs in the console now at least saying that "you must be a player"

**Comment by 128912891289** [comment]
These are the errors I get: ![image](https://github.com/sekwah41/Advanced-Portals/assets/63319015/fea53b8e-1659-47ff-ae30-4c34a89bd75a)

**Comment by sekwah41** [comment]
Now thatll be your permission manager, by default op will allow you certain perms but stuff like luckperms you can overwrite that. Please ensure you have perms such as advancedportals.*

**Comment by 128912891289** [comment]
Turns out it was a permissions issue. I did actually have advancedportals.* and was op (I did a combination of them), but after removing LuckPerms on my test server and just staying op it seemed to work. Thanks for all of your help.

**Comment by sekwah41** [comment]
Its no worries :) its not always clear what the cause of a problem is.
