### ISSUE TITLE
Issues with velocity

### ISSUE THREAD

**Issue by sekwah41** [sekwah41/Advanced-Portals#391]
So far this has been reported on the discord and looks like a genuine issue rather than plugin clash, will need to investigate.

**Comment by celciusjj** [comment]
Using velocity in proxy #276 https://papermc.io/downloads/velocity
Using paper 1.20.2 

I have two servers, RPG and PROVINCIA. each one has 2 portals and 2 destinations.

Config files:

https://pastebin.com/AGtSj4M7

Provincia files (Portals and destination)

https://pastebin.com/aSJwPUpc

Rpg files (Portals and destination)

https://pastebin.com/N1G1cgyj

Video with all plugins installed on my servers.
https://www.youtube.com/watch?v=9AEKRUGpCC0

Description:

- i travel to dungeons and works well.
- i travel to voras and works well.
- i travel to dungeons trougth dungeons portal and the portal took me to voras, not the destination, to the last position in server RPG, IS WRONG.

We try without plugins now. No plugins in velocity, no plugins in paper servers.

this is the result:

![image](https://github.com/sekwah41/Advanced-Portals/assets/37490999/0466f452-570c-4159-8293-2045d7e95aa4)

![image](https://github.com/sekwah41/Advanced-Portals/assets/37490999/7a9326ed-4815-4093-9708-23865e115587)

**Comment by celciusjj** [comment]
If you need some server to test the plugin, i am available. 

Discord: celciusdev

**Comment by EmanYm** [comment]
`Velocity 3.2.0-SNAPSHOT (git-19abb909-b265)`
`Loaded plugin advancedportals 0.9.3`

It works without error

**Comment by celciusjj** [comment]
> `Velocity 3.2.0-SNAPSHOT (git-19abb909-b265)` `Loaded plugin advancedportals 0.9.3`
> 
> It works without error

You can travel between server to specific position right?

**Comment by sekwah41** [comment]
I believe I forgot this issue existed on github. From my testing you can move between servers and to locations via velocity last I checked.

**Comment by celciusjj** [comment]
This is my schema

![image](https://github.com/sekwah41/Advanced-Portals/assets/37490999/f53da2cd-1a45-46a1-856b-7fa798ba40ce)

**Comment by sekwah41** [comment]
Testing on latest seems to be fine from my end at least.

**Comment by celciusjj** [comment]
Resolved, was a problem with compability with mmoprofiles @sekwah41

**Comment by sekwah41** [comment]
Seems to be mostly be fixed and I have tested it in the latest versions. If you need to force enable it check the config.yml :)
