### ISSUE TITLE
[BUG] RUT ROH RAGGY what's a RAG

### ISSUE THREAD

**Issue by CKY-** [sekwah41/Advanced-Portals#395]
I was looking for something to help a friend with another issue and RUH ROH I needs to know what a rag is? 

https://github.com/sekwah41/Advanced-Portals/blame/24d05ff2fd26692666900f7fe8bcabe66ca712a3/src/main/java/com/sekwah/advancedportals/bukkit/api/warphandler/TagHandler.java#L75

**Comment by TreemanKing** [comment]
Seems like a typo.

**Comment by sekwah41** [comment]
Im surprised ive never noticed this

**Comment by sekwah41** [comment]
Ah now I know why it wasnt noticed, this file is only used in the re-code branch. its never actually used in this branch.
