### ISSUE TITLE
Create a gradle.build file

### ISSUE THREAD

**Issue by sekwah41** [sekwah41/Advanced-Portals#40]
Once I've read over the gradle userguide gradle support needs to be added.

**Comment by Maxqia** [comment]
We already have maven, They're both build systems, so it's usually one or the other.

**Comment by sekwah41** [comment]
True, I was origionally going to go with gradle over maven for some reason but the current set up seems pretty simple and nice now im getting more used to it xD. The multi dependency thing was annoying me for craftbukkit versions but now I've fixed it with reflection maven is perfect and you don't even need to compile a craftbukkit version. (However it helps for testing before converting the code to work with reflection)
