### ISSUE TITLE
Advanced Portals and NappyCraft

### ISSUE THREAD

**Issue by TheShadowModsUK** [sekwah41/Advanced-Portals#407]
Hey there, I would like to know how your handling the portals/TP as my mod what is forge I know yours is spigot but when I walk though your portals it's messing with local variables for some strange reason and making the players item beforing damaged.

In this case it's making the nappy wet this does not happen using normal portals or tp mods or plugins, I don't believe this is my error as I never seen this before, but until I know how your handling it I can't even make a part my side or ask you to patch it your side.

**Comment by sekwah41** [comment]
Given the fact it's not currently a forge mod and interacts solely with the bukkit API, you'd need to check how the teleportation is handled through whatever compatibility layer you are using to load spigot/bukkit plugins.

The method used is player.teleport

Given the behaviour you have described, it doesn't sound possible given the methods/APIs I interact with, so you'd need to talk to the people who make the compatibility layer or possibly get them involved in this discussion.

There is a re-code I've mostly finished, which I do plan to add forge/fabric support to directly, though I still need to finish its spigot version.

**Comment by sekwah41** [comment]
I will admit the old code is very messy, though the only interactions with the portals in the old version at least are that player.teleport event, cancelling some events for things like combustible to help with lava portals and a few things to stop damage from fire sources otherwise. There is nothing that I could see causing damage or affecting items even by a side effect; otherwise, it would cause issues to vanilla items, too.

Let me know if you find any more info or would like to ask about anything else, and I'll let you know what I can.

**Comment by TheShadowModsUK** [comment]
> I will admit the old code is very messy, though the only interactions with the portals in the old version at least are that player.teleport event, cancelling some events for things like combustible to help with lava portals and a few things to stop damage from fire sources otherwise. There is nothing that I could see causing damage or affecting items even by a side effect; otherwise, it would cause issues to vanilla items, too.
> 
> Let me know if you find any more info or would like to ask about anything else, and I'll let you know what I can.

From my tests I understand what your saying your plugin wasn't the only one creating this problem the damage created to my item is because the player data verbs are not been past across to the new world right, doing a world jump is doing this damage, but mods that handle the tp more like a dimension tp where it pulls the player data with it.

I had to drop the hybrid server at this time as there was just other bugs what right now created problems worse then this one, I am sorry I didn't jump back and let you know other plugins was having the same problem I been busy with mod/the server and other things like proxies lol

If you do create a Forge build let me know I will test it for sure but the problem is the player data what is Player persistent and other set data isn't passed across or have a option to be passed acorss

**Comment by sekwah41** [comment]
Closed for now as it was an issue with the compatibility layer
