### ISSUE TITLE
How to add permisson to non op players to create portals?

### ISSUE THREAD

**Issue by Zangour0** [sekwah41/Advanced-Portals#408]
I whonder to know how to add permission to no op players to create portals

**Comment by sekwah41** [comment]
id suggest turning off command portals if you want to allow that, though the permissions would be 

advancedportals.createportal
advancedportals.portal
advancedportals.desti

Tough i may be wrong or may need to alter them a bit

**Comment by sekwah41** [comment]
Permissions have been reworked. I'd still needed check them.
