### ISSUE TITLE
java null error

### ISSUE THREAD

**Issue by cyberwarp535** [sekwah41/Advanced-Portals#41]
I have encountered a bug that creates a large number of java null errors. Basicly when I set up the plugin and number only the blocks they throw a large number of java null errors that show in the log file and creates a huge log file. when I deleted the numbering and started with name and name/number this bug goes away. It may be recomended to put in the readme file not to use just numbers or find why this bug is happening. attached is log file.
[2016-08-01-8.log.gz](https://github.com/sekwah41/Advanced-Portals/files/397251/2016-08-01-8.log.gz)

EDIT: FOrgot to put in that I am using Spigot 1.10.2 (built from tool on web site) with advancedportals, antilag, backpacks, enderdragonrespawner, essentials 2.x, essentialsspawn 2.x, silkspawner, worldedit, and zpermissions for plugins besides this one.

**Comment by Maxqia** [comment]
It's already fixed in git and should be fixed in the next version of Advanced Portals that's released.

**Comment by cyberwarp535** [comment]
Thank you
