### ISSUE TITLE
Command doesn't issue on portal creation

### ISSUE THREAD

**Issue by TreemanKing** [sekwah41/Advanced-Portals#424]
String created in configuration is "literal" and not an actual string.

For example 
```yml
'#say minecraft:say test'
```
Rather than
```yml
"#say minecraft:say test"
```

**Comment by sekwah41** [comment]
This is more an issue of how yaml reads but may be altered in the recode.

**Comment by TreemanKing** [comment]
From my testing, it's based off the java version the server it runs in. In
newer versions, " " works but ' ' doesn't register a strong whereas in Java
8, it registers both.
