### ISSUE TITLE
Portal block crash

### ISSUE THREAD

**Issue by lolwhatdidigetbanned** [sekwah41/Advanced-Portals#437]
When you get a portal block or gateway or anything, I’m stuck on timeout

**Comment by lolwhatdidigetbanned** [comment]
> > When you get a portal block or gateway or anything, I’m stuck on timeout
> 
> Can you provide more details.
> 
> Plugins, server version, AP version. Thanks.

FastAsyncWorldEdit, latest server version (1.21), latest AP version https://modrinth.com/plugin/advanced-portals/version/1.0.0

**Comment by TreemanKing** [comment]
I was not able to replicate this. I was able to use all three portal blocks without any crash occurring and they all placed as well.

**Comment by sekwah41** [comment]
Please provide a video showing us the issue so we are able to get more information as to what is going on

**Comment by sekwah41** [comment]
Also what fork of the server are you using? spigot, paper, purpur?

**Comment by lolwhatdidigetbanned** [comment]
Purpur, only slicehosting.tech this error happening bedrock edition

**Comment by TreemanKing** [comment]
We don't officially support Geyser/Bedrock support.

**Comment by sekwah41** [comment]
Closing for now as if there are issues with gyser the you need to raise it with them not us. If you are able to recreate it using a java client feel free to ask me to reopen this or submit some evidence to help us recreate it.
