### ISSUE TITLE
Command executed via portals issue

### ISSUE THREAD

**Issue by dubbz2** [sekwah41/Advanced-Portals#438]
Hello, i am coupling this plugin with the multiverse plugin. I am also trying to couple this plugin with better rtp. However Ihave noticed that when the command i am wanting the portal to execute happens to have a space in it it doesn't not work at all. the is the Create command I was trying to use to make an rtp portal: /portal create name:RTP triggerblock:water command:"/rtp world world"  
However when I tried using the command feature with a command containing no spaces it worked like a charm. Is there something i need to substitute the space for in order for this to work? like a period or dash? Not sure what the issue is.

**Comment by TreemanKing** [comment]
> Hello, i am coupling this plugin with the multiverse plugin. I am also trying to couple this plugin with better rtp. However Ihave noticed that when the command i am wanting the portal to execute happens to have a space in it it doesn't not work at all. the is the Create command I was trying to use to make an rtp portal: /portal create name:RTP triggerblock:water command:"/rtp world world"  
> However when I tried using the command feature with a command containing no spaces it worked like a charm. Is there something i need to substitute the space for in order for this to work? like a period or dash? Not sure what the issue is.

Hey mate, it looks pretty good but you don't need the /. Instead it should look like `/portal create name:RTP triggerblock:water command:"#rtp @player world"`
Where @player signifies the player entering the portal and # means it is executed by the console. 

If you have any trouble, I'd recommend joining the discord.

**Comment by TreemanKing** [comment]
@sekwah41 Can be closed.
