### ISSUE TITLE
ProtocolLib / WorldEdit

### ISSUE THREAD

**Issue by Maxqia** [sekwah41/Advanced-Portals#44]
What do you think of using ProtocolLib and WorldEdit instead of using the custom stuff we have now?

**Comment by sekwah41** [comment]
Protocol lib i dont really want to rely on because it takes longer to update. Tbh the reflection we have atm is perfectly fine. And world edit we could add but it stops it being a necessity. Personally I like the not relying on other plugins.

**Comment by sekwah41** [comment]
ProtocolLib wont be needed due to new additions however I will look at world edit though I may just keep it all included.
