### ISSUE TITLE
Could you add support for folia 1.20.6 pls

### ISSUE THREAD

**Issue by Jim-m-y** [sekwah41/Advanced-Portals#440]
Could you add support for folia 1.20.6 pls, it would be something very cool, my folia server is growing with more than 800 active users on that server alone and it would be nice to have this plugin available

**Comment by sekwah41** [comment]
Last I checked folia didn't even support some of the core events we needed to finish off the plugin for nether portals and such.

Folia seems very early access and lacking in features so we left the branch in limbo for now.

I'll be busy for the next week but I'll see when I can if those events have finally been implemented.

**Comment by rautamiekka** [comment]
> Last I checked folia didn't even support some of the core events we needed to finish off the plugin for nether portals and such.

All the better reason to make a report.

> Folia seems very early access

Yeah, they even shamelessly lie about download availability. TBF, probly to avoid useless tickets from every type of an idiot.

**Comment by sekwah41** [comment]
[Advanced-Portals-0.9.3.zip](https://github.com/user-attachments/files/16735145/Advanced-Portals-0.9.3.zip) this is an old fork i made to test folia, the issue  is portal events don't exist so you'll be able to do gateway blocks in the overworld, lava or water portals.

I don't have any plans to add full support until they do a proper release, as it's extra maintenance for a system that has many issues I cant fix.

If its got everything and works fine I can test and see but the project seems too early to fully support.

**Comment by sekwah41** [comment]
Closing for now. Will re-open if any more info is added or its confirmed that folia has the required events to support the plugin. To my knowledge that copy I made here should work to test though I don't have the time to test myself.
