### ISSUE TITLE
Plugin causing lag and mspt spikes.

### ISSUE THREAD

**Issue by matipoirierg** [sekwah41/Advanced-Portals#446]
https://spark.lucko.me/hZPXWAhqob

**Comment by TreemanKing** [comment]
Duplicate of #439

**Comment by sekwah41** [comment]
Same place different issue. This one is due to incredible inefficient reading of the file entities by spigot.

Paper and its forks have a Boolean you can pass in to avoid this spike but I haven't implemented any paper specific performance improvements yet.

**Comment by sekwah41** [comment]
This even has been removed
