### ISSUE TITLE
Using triggerblock PORTAL will teleport you to the nether when using the command variable.

### ISSUE THREAD

**Issue by Markersx** [sekwah41/Advanced-Portals#46]
If I have permission to the command it teleport me to the nether sometimes but if I don't have permission to use the command it always teleport me to the nether. For example if i create a portal with this command /portal create name:portal command:"spawn" but they don't have permission for /spawn it will teleport them to the nether.

**Comment by sekwah41** [comment]
ill have to check that out, it seems like an odd bug that shouldnt happen at any possible time. It it only when in creative?

**Comment by sekwah41** [comment]
Issue should be fixed now
