### ISSUE TITLE
feat: show visualiser

### ISSUE THREAD

**Issue by sekwah41** [sekwah41/Advanced-Portals#465]
Need to either switch back over to using stained glass for spigot, or take a look at how to more, reliably send the debug packets.

Maybe via protocol lib and just make the feature depend on it? Wouldnt be a bad shout

**Comment by rautamiekka** [comment]
See if [https://github.com/MrMicky-FR/WorldEditSelectionVisualizer](https://github.com/MrMicky-FR/WorldEditSelectionVisualizer)'s code would be useful.

**Comment by sekwah41** [comment]
@rautamiekka  they are using particles, which honestly is a really cool idea and may be good for older versions which don't support the feature I'm mentioning, though for this I'm specifically talking about

![image](https://github.com/user-attachments/assets/0db58860-1aed-42d1-8b18-940ebde187c4)

**Comment by sekwah41** [comment]
I think I'll take a look at a particle based visualiser at some point as a backup. Or might switch over to that solely if this is being a pain.

**Comment by AlastairVisku** [comment]
Actually, I am going to re-do this with particles; looking at the different versions, it looks like the way these debug packets are done varies too much between different versions of the game to reliably do nicely. I may re-visit it but its not worth the effort to have something that will likely break every few versions :(

**Comment by sekwah41** [comment]
Actually, I am going to re-do this with particles; looking at the different versions, it looks like the way these debug packets are done varies too much between different versions of the game to reliably do nicely. I may re-visit it but its not worth the effort to have something that will likely break every few versions :(

**Comment by sekwah41** [comment]
What I'll do is add something like this back when I make the forge version as a client side optional mod.

**Comment by sekwah41** [comment]
![image](https://github.com/user-attachments/assets/1f509726-7bb9-4c13-8d9a-40fa1a2a2978)
![image](https://github.com/user-attachments/assets/296743ca-6480-4f21-886b-41efca1a4fd8)
![image](https://github.com/user-attachments/assets/c1fad4a1-4565-4855-bd84-37a47ae4eaa4)
