### ISSUE TITLE
Translate warp message [FEATURE]

### ISSUE THREAD

**Issue by maxlehot1234** [sekwah41/Advanced-Portals#47]
Hi, is it possible toadd the warp message inside the config.yml so I can translate it?

Thank you

**Comment by sekwah41** [comment]
I thought it was already there. Ill take a look.

**Comment by sekwah41** [comment]
I will create a specific lang file while recoding to hold most of the user seen messages.

**Comment by sekwah41** [comment]
I assigned the wrong person xD

**Comment by sekwah41** [comment]
A full translation feature has been added into the re-code and is fully working.
