### ISSUE TITLE
bug: log feedback spam

### ISSUE THREAD

**Issue by TreemanKing** [sekwah41/Advanced-Portals#495]
When creating a portal and putting a destination that doesn't exist, it will spam log even though the command hasn't been outputted. For e.g. 

![image](https://github.com/user-attachments/assets/545982b4-a956-4f76-b86f-824f280ccef1)

Reproduce steps:
1. /aportals create name:test desti:test1234567890 
2. it will show the above screenshot

It is best that we leave it until after the command is processed.

**Comment by sekwah41** [comment]
Tbh, we don't need that log, but we should probably be caching the list if it's not. I'll check the code and disable the log
