### ISSUE TITLE
World portals

### ISSUE THREAD

**Issue by sekwah41** [sekwah41/Advanced-Portals#54]
Suggestion from Sequacious

Love the plugin, just have a feature request although it's totally cool if you don't want to do it.
Would it be possible to have portals act like Nether Portals but for a world the user defines?
e.g 
I have the worlds
Overworld
Aether
Overworld_nether
Overworld_the_end
I define a portal in Advanced Portals, and it acts like Nether portals do, but only for the Aether world

**Comment by bc-hill** [comment]
If using Multiverse, this is already available.
https://dev.bukkit.org/projects/multiverse-netherportals
