### ISSUE TITLE
No Permission

### ISSUE THREAD

**Issue by xBoneso** [sekwah41/Advanced-Portals#56]
Hello, i created a portal with a destination and the portal did not have permissions set, so anyone could use it, but When users go in it it says they don't have permission i really need help, Thanks.

**Comment by sekwah41** [comment]
What version are you using?

**Comment by xBoneso** [comment]
1.11

**Comment by xBoneso** [comment]
Can you please help? I really need this plugin because it's the only portal plugin that allows teleporting using air and that has particles and awesome features. I love this plugin

**Comment by sekwah41** [comment]
I meant of my plugin not minecraft. Also i haven't tested it with 1.11 mc yet for the latest.

**Comment by xBoneso** [comment]
I use the latest aka 0.0.23

**Comment by sekwah41** [comment]
Il test myself this weekend. I tested it for that before uploading tbh.

**Comment by xBoneso** [comment]
Did it get fixed?

**Comment by sekwah41** [comment]
Sorry i was busy with a hackathon :P i said id test this weekend

**Comment by xBoneso** [comment]
Alright, please tell me when it's fixed.

**Comment by sekwah41** [comment]
Sorry i forgot to message here, I am pretty sure it is fixed now.
