### ISSUE TITLE
Broken Sugar_Cane TriggerBlock. in 1.11 its renamed to REEDS

### ISSUE THREAD

**Issue by Bodyash** [sekwah41/Advanced-Portals#57]
Broken Sugar_Cane TriggerBlock. in 1.11 its renamed to REEDS

CANT Create portal with that trigger

**Comment by sekwah41** [comment]
As long as the name is what is in minecraft it will work, it is not on me to make them work with specific names. It is built into base minecraft. Ill take a look to check but as long as you have the blocks material string identifier it will work. Its on the spigot team and mojang as in what names change between versions, not me.
