### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by crimilo** [sekwah41/Advanced-Portals#58]
i wanna try to use command /servers to show the server GUI but doesn't work
i do /portal create name:Servers triggerblock: water command:"!Servers"
and doesn't open the GUI how can i do?

ChestCommands conf:
######################
#+                  +#
#   MENU SETTINGS    #
#+                  +#
######################

menu-settings:

  # name - appears as the title - REQUIRED
  name: '&2&lAbstractMc &a&lNetwork'

  # rows - the number of rows of the chest - REQUIRED
  rows: 3

  # command - OPTIONAL (you can remove this or set it to '')
  # Bind multiple commands using ; (command: 'menu; m; me')
  command: 'servers; server'

  # auto-refresh - OPTIONAL
  # How frequently the menu will be refreshed, in seconds.
  # Useful if you have variables in items' descriptions.
  auto-refresh: 5

  # This command command will be execute when the menu is opened.
  # Supports all the icon command types.
  open-action: 'sound: note pling;'

  # open-with-item - OPTIONAL
  # The menu will open only right-clicking with orange wool [35:1]
  open-with-item:
    id: 345
    left-click: false
    right-click: true

######################
#+                  +#
#       ITEMS        #
#+                  +#
######################

KitPvP:
  COMMAND: 'server KitPvP'
  NAME: '&cKitPvP'
  LORE:
    - '&7Clicca per entrare nel KitPvP!'
  ID: 276
  POSITION-X: 5
  POSITION-Y: 2

ERROR AdvancedPortals:
[14:04:10 ERROR]: [AdvancedPortals] Portal command: !servers
[14:04:10 INFO]: [AdvancedPortals] Servers:null

**Comment by sekwah41** [comment]
Which version of the plugin are you using?

**Comment by crimilo** [comment]
0.0.13

Inviato da Posta per Windows 10

Da: sekwah41
Inviato: mercoledì 17 maggio 2017 02:01
A: sekwah41/Advanced-Portals
Cc: crimilo; Author
Oggetto: Re: [sekwah41/Advanced-Portals] ERROR (#58)

Which version of the plugin are you using?

**Comment by sekwah41** [comment]
Well that version does not work with any command that teleports you or brings up a gui. The newer versions do however ;)

If you are using such an old version the version of mc you are using may become an issue however.
