### ISSUE TITLE
Movment Error

### ISSUE THREAD

**Issue by joshua31177** [sekwah41/Advanced-Portals#61]
https://hastebin.com/ufupudupur.vbs

**Comment by sekwah41** [comment]
This bug has already been fixed. If it is in 0.0.27 still then message here.

**Comment by joshua31177** [comment]
I am on 0.0.26 because 0.0.27 has not been released yet.

**Comment by joshua31177** [comment]
so what am I supposed to do remove the plugin until 0.0.27 gets released?

**Comment by sekwah41** [comment]
I missnumbered on spigot the most recent one is actually 0.0.27 and it shows when you download.

**Comment by sekwah41** [comment]
I got the version numbers wrong. Which version of mc are you on?

**Comment by sekwah41** [comment]
Fixed now I will be uploading a 0.0.27 now

**Comment by joshua31177** [comment]
I am on version 1.11.2

**Comment by sekwah41** [comment]
If this is still an issue please tell me

**Comment by joshua31177** [comment]
It seems to be an issue Again.

**Comment by joshua31177** [comment]
I don't know why.

**Comment by sekwah41** [comment]
Same version of mc on the newest build?

**Comment by joshua31177** [comment]
same version 1.11.2

**Comment by joshua31177** [comment]
lastest build of 1.11.2 I belive

**Comment by sekwah41** [comment]
Tested on the latest version with 1.11.2 and i cant replicate this error
