### ISSUE TITLE
fly being enabled?

### ISSUE THREAD

**Issue by smmmadden** [sekwah41/Advanced-Portals#62]
Hi, I just started using the Advanced Portals 0.0.26 for my Bungee network of about 7 worlds.  It took me a bit to figure out the syntax and watch the video on the spigot page.  I got the portals working but one thing I've noticed is if I go through a portal in World A and end up in World B everything works just fine.  However, if I use the /server command or alias /thehub I do end up back to World A, but not touching the ground and in the air one block higher like it enabled "fly" permission which I do have, but normally I have to use the /fly command to enable it.  Not sure if it is Bungee doing this or if it is the AdvancedPortal.  I wasn't getting the same behavior before using the portal though.  One way to reproduce it is to go through the portal, then go back to the Lobby (or another world) with the /server command.  Then just move your mouse slightly and you get pushed back and in the air. :-)

**Comment by sekwah41** [comment]
My plugin has nothing to do with setting fly on the players. That is solely due to the player joining and quitting when being moved from bungee.

**Comment by smmmadden** [comment]
you may not have understood the issue.  

If I use the /server (bungee command) to go to each world, there are no issues with it - it works and feet are on the ground.

If I go through a portal to another world, it works fine and my feet are on the ground.  But if I use the /server command to get back to the world I came from, I'm floating 1 block higher than I should be and simply moving my mouse to look left/right I bounce backwards.

How could this be a bungee issue if this only happens after going through the portal and returning?  I'm happy to report it to Spigot, but you know they'll just say its the plugin since it was used first.

**Comment by smmmadden** [comment]
Here is a screen shot of me floating after going thru the portal and coming back.
![image](https://cloud.githubusercontent.com/assets/10309346/26289206/fb58e2f4-3e6b-11e7-8fac-0c9d6ac6cf58.png)
Doesn't matter whether the portal is a PORTAL or WATER, the same behavior above is seen.

**Comment by smmmadden** [comment]
I found out what the problem was, the default values for this in the config.yml
ThrowbackAmount: 0.7 # How fast to throw them back, 0 or lower to disable throwback
Apparently, the .7 meant to push me up 3/4 of a block higher and push me back when I move my mouse.  This may have been the original intent, but having it throw you back shouldn't change your Y location too.  Once I set this to 0 on all the worlds, I'm a) no longer thrown backwards and no longer floating in air.  I would still see the air part a bug, since not all worlds will have FLY enabled which is what this mimics.  There is no option that I know of that allows a player to float. :-)

**Comment by sekwah41** [comment]
I'm still confused at what's wrong with your setup/what bungee is doing or what you are trying to say.

**Comment by smmmadden** [comment]
Okay, let me describe it differently then. :-)
1. ThrowbackAmount: 0.7 # How fast to throw them back, 0 or lower to disable throwback
Leaving this value set to .7 does what the name says - throw the player backwards at 3/4 speed assuming 1.0 is the fastest.  This works!

However in bungeecord setup Going through the portal from the lobby (WorldA) to any other world (say WorldC), that works fine.  No throwback initiated or felt.  However, typing in /server WorldA will get me back to the lobby (WorldA), but I'm floating about 1 block higher than I should be.  Any movement of my mouse with the player activates the throwbackamount variable and I get pushed backwards quickly (but still floating).  The pictures above show me floating one block up and I didn't use /fly yet (to enable me to fly).

Now, if I set up a portal in WorldC to go back to WorldA, everything works fine.  I believe it may have something to do with what /server xxxx command that may not be calling the same code it should?? Pure guess on my part here, just trying to understand the mechanics and why it does what it does.

**Comment by sekwah41** [comment]
Bungee swap commands are solely packets that tell the server to move the user, it should be the same as /server
