### ISSUE TITLE
triggerblock list?

### ISSUE THREAD

**Issue by smmmadden** [sekwah41/Advanced-Portals#63]
Do you have a list of triggerblock values that can be used for the portal?  I understand that water, lava, portal can be used, but is there a larger list of blocks to be used?  Didn't see it on the Wiki page, so I'm just looking for what works or doesn't.  - Thanks! Steve

**Comment by sekwah41** [comment]
It is the default mc names so for example quartz stairs is QUARTZ_STAIRS, check what the name is you would need to use /give for or i think you can see it if you press f3+h then hover your mouse over the block in your inventory.

**Comment by sekwah41** [comment]
http://puu.sh/w2ZCH/015da1ce7d.txt

There is a list directly from spigot. Some of those are items though

**Comment by sekwah41** [comment]
Just ignore anything in brackets and use the variable names.

**Comment by smmmadden** [comment]
Great, thanks for the list, that helps quite a lot. :-)
