### ISSUE TITLE
selector

### ISSUE THREAD

**Issue by samlolol1** [sekwah41/Advanced-Portals#64]
i try to select region for the portal i do /ap selector
i got the selector but when i try to select a block its break the block and does not do anything..
please help
-thakns!

**Comment by sekwah41** [comment]
Which version of MC?

**Comment by samlolol1** [comment]
1.8

**Comment by samlolol1** [comment]
please help? :(

**Comment by Sabishi1985** [comment]
Spigot-server, version 1.11, same problem. I can't select anything with the selector. It just works like a normal tool. :-/

**Comment by sekwah41** [comment]
Ill check that out. Strange >.>

**Comment by Sabishi1985** [comment]
Just a quick update on the problem: I went back to version v0.0.24 and tadaaa: It works! (Tried v0.0.28 before)

**Comment by nomis8952** [comment]
have you found out what is causing this issue

**Comment by sekwah41** [comment]
Ive been busy the past few days, i can check tomorrow if i rememebr

**Comment by sekwah41** [comment]
Just tested, the selector works in 1.8.9, 1.11 and 1.12 from my tests so far of default spigot. I need a little more info such as extra plugins you have. Try deleting the plugin config in case the axe material is bugged, though that shouldnt cause any issues.

**Comment by sekwah41** [comment]
try the newest version i changed the order of some stuff
