### ISSUE TITLE
Portal creation error, portals must not overlap

### ISSUE THREAD

**Issue by smmmadden** [sekwah41/Advanced-Portals#65]
Not sure if this is a user error or just a bug.  But I have an AIR block portal to take me to another world and that works fine.  When I add a second one 2 blocks away, I get a Portal creation error, portals must not overlap!
![image](https://cloud.githubusercontent.com/assets/10309346/26353519/cfe79cd6-3f8e-11e7-8f4d-4314434a6bf9.png)
When I selected the 1 block area for the portal on the left, I clicked the left block (wall) and the right block (next to the Quartz Block).  Should I be placing a block where the AIR is, selecting only it or is this a bug?  Thanks! -Steve

**Comment by sekwah41** [comment]
use "/portal select" and punch the two corners, if a portal is selected then you have a portal in that region. That is the only way that message can occur. Remember if you want the portal to be 1 block you need position 1 and 2 to be the same block as 1 and 2 is used to create the region.

**Comment by smmmadden** [comment]
Thanks, I had it occur on another portal and realized that the selections were done left/right when a single block like you said is either back and front or the same block as 1 & 2. :-)

**Comment by sekwah41** [comment]
Great it was solved :)
