### ISSUE TITLE
You need permission to make a op command portal!

### ISSUE THREAD

**Issue by crimilo** [sekwah41/Advanced-Portals#66]
i cannot create command:"!servers" to open chestcommands servers GUI because i have no this permission how can i do?

FOOTER CONFIG:

CommandLevels: o

**Comment by sekwah41** [comment]
you need o and h so oh for admins to be able to make the portals without perms

also thats a bungee command, its caught by bungee not the server so it wont work

**Comment by crimilo** [comment]
so what can i do? can you tell me step by step?

**Comment by sekwah41** [comment]
Change the config to say CommandLevels: oh and you are done

Then just try to make the portal again.

**Comment by crimilo** [comment]
works......but doese not work the command says'unkown command. type /help for help.

**Comment by sekwah41** [comment]
As I thought, its a bungee command. It executes the commands on the server directly as the player. Not through the bungee.
