### ISSUE TITLE
Triggerblock End_Portal Still Not Working

### ISSUE THREAD

**Issue by Romanthefrog10** [sekwah41/Advanced-Portals#67]
Im Trying to add the triggerblock as triggerblock: end_portal but isnt working =( but that id works with worldedit and stuff

**Comment by sekwah41** [comment]
dont put a space between it

**Comment by Romanthefrog10** [comment]
k thx ill try =D

**Comment by Romanthefrog10** [comment]
didnt work =(

**Comment by sekwah41** [comment]
Strange, it should be whatever it is in minecraft with the /setblock command or /give :P

**Comment by sekwah41** [comment]
ahh, there its that you arnt using the right block name. it is END_GATEWAY and the normal portal is ENDER_PORTAL

**Comment by Romanthefrog10** [comment]
Thx
