### ISSUE TITLE
Bungee leave location

### ISSUE THREAD

**Issue by sekwah41** [sekwah41/Advanced-Portals#68]
Set the location of the player when the player leaves

**Comment by krustymk** [comment]
Bungee support tp's player back to the portal and not to the world spawn or to a destination, unable to set destination on the bungeecord world

**Comment by sekwah41** [comment]
Hmm. I'll have to check that. It used to just basically log you back into the server you were being moved to.

**Comment by krustymk** [comment]
yes but if you left via a portal when you return you appear back in the portal, not at spawn

**Comment by sekwah41** [comment]
Well if you log out of a server then log back in does it put you back at the spawn? Its the same process

**Comment by krustymk** [comment]
No, if i log out i log back in at the same point
If the player dies, they appear at spawn
If the player leaves the server via a portal, they shouldnt appear back inside the portal on return yet they do

**Comment by sekwah41** [comment]
You are missunderstand.

I haven't changed anything about the player moving on leave. I should probably thinking about it though based off current behaviour of how bungee works it just logs the player out of a server and into another. The player isn't being killed so why would it respawn?

I'm unsure ATM if you are saying it's not doing it and should or if you are saying you want this to be added.

**Comment by krustymk** [comment]
imo
when going to another server via the portal, it should either transport you to a specified destination or if one isnt available then spawn. 

If thats not how it should be, then yes if possible i would like that to be added :)
