### ISSUE TITLE
Portal Tags

### ISSUE THREAD

**Issue by Fordy436** [sekwah41/Advanced-Portals#72]
After selecting two points for my portal and then trying the following command: 
/portals create PvE command:"^warp pvespawn"

I got the lack of permissions message, even though I'm OP. I got the same message with trying to get it to run a console command as well as an op command (command:"#warp pvespawn" and command:"!warp pvespawn").

I thought directly giving me the permission advancedportals.create would solve the issue, but that didn't work either.

Latest version installed. Running Spigot 1.12.

**Comment by sekwah41** [comment]
Check the plugin config. I will add something to the wiki soon. Also I did a reply on the spigot forum to someone with a similar issue.

**Comment by Fordy436** [comment]
I dont understand the config. Can several letters be used or can I only select one?

I see:
# h Ops can create admin commands without special perms
# e Ops can create all perm commands without special perms
# k Ops can create console commands without special perms

But I want ops to create all of them.

**Comment by sekwah41** [comment]
You can use multiple
