### ISSUE TITLE
Delay before teleport

### ISSUE THREAD

**Issue by sajphon** [sekwah41/Advanced-Portals#77]
Hey! :)
First of all i love the plugin! :+1: 

Second, please, could you add option to set time delay the player needs to stand in the portal before it teleports him away? 
Because it is quite useful to have walkthrough portals, but with instant teleportation it is not possible.
Thank you.

**Comment by sekwah41** [comment]
It would be annoying to code nicely based off the current portal code though I can think of two ways to do it nicely. The thing is this is quite a specific feature that I don't think a lot of people would need so it's not going to be high on the list right now. Sorry.

**Comment by sekwah41** [comment]
Why do you need walkthrough portals?

**Comment by LeotomasMC** [comment]
A vanilla nether portal acts like this, you can make a cool doorway with a portal. And it serves as a portal

**Comment by sekwah41** [comment]
@LeotomasMC actually good point, that has an event and I could swap it to listen just for that if a flag is changed :)

**Comment by sekwah41** [comment]
After all this time you can now add the delayed: tag to be true or false. It will be available in 0.0.51
