### ISSUE TITLE
commands and permissions dont work together + portal transport issues

### ISSUE THREAD

**Issue by Scorpionvssub** [sekwah41/Advanced-Portals#78]
As i've mentioned in your pm box, I made 2 portals 1 with nether portals 1 with ender.
My nether = survival
Ender = creative

However creative teleports me to survival while the bungee in config is set to creative?
Also when teleport it says: fallback server may have crashed or some weird stuff like that....

As with all "bungee" portal plugins they all say that but players can just do /survival /creative etc without ANY issues or added msgs of server being down.

Also speaking of commands... i tried all permissions and none allow me to create command portals

**Comment by sekwah41** [comment]
You enable command portals in the config. Its not just permissions. Also that is on your bungee setup not my plugin. All my plugin does is send a switch server request.

**Comment by Scorpionvssub** [comment]
no option there.

**Comment by sekwah41** [comment]
yes there is at the very bottom of the file. If you have an old version you need to update the config.

**Comment by Scorpionvssub** [comment]
i downloaded it 15 mins ago or something

**Comment by sekwah41** [comment]
If you op the players after enabling the o and k they should be able to make op portals
