### ISSUE TITLE
seem not support UTF-8

### ISSUE THREAD

**Issue by khlfkk** [sekwah41/Advanced-Portals#79]
after restart the ser, the  string became --> ??????

**Comment by sekwah41** [comment]
the config readers are default bukkit, anything that works for others will work with this as well as the actual default files are UTF-8 this is an error with you not saving it as UTF-8.

**Comment by sekwah41** [comment]
This isnt a bug directly with my plugin as it doesnt read configs itsself thats why I closed this. I will still try to find out what is going on and try to fix this.

"#tellraw @a {"text":"➜玩家 @Player 前往安徒生世界","color":"green","italic":false}

then after restart it will show ??????????????????? <--- , May i know that is it support UTF-8 string? Thankyou"

Message from spigot

**Comment by samueleycw** [comment]
I confirmed which all message file is saved as UTF-8. btw, thankyou for your help:)

**Comment by sekwah41** [comment]
Wait does it work or still not?

**Comment by samueleycw** [comment]
still not ,thanks

**Comment by sekwah41** [comment]
Sorry :P

**Comment by sekwah41** [comment]
This seems to work though I am unsure why it didn't or mc sometimes doesn't seem to like it.
