### ISSUE TITLE
ChestCommands possibly not working with plugin

### ISSUE THREAD

**Issue by sekwah41** [sekwah41/Advanced-Portals#80]
See reference back to when gui commands were not working see #52 which has not been brought up for a long time so I thought the old changes fixed that.

**Comment by ItsCursed** [comment]
k

**Comment by ItsCursed** [comment]
The plugins' not working with ChestCommands for sure and the issue #52 was closed because the person who was asking never replied while the Author said it'll be fixed in the next update and closed the issue for the person for not being active, I need help on that!

**Comment by sekwah41** [comment]
Gui's are removed by standing in portals. Do not use default triggers for gui commands.
