### ISSUE TITLE
"permission" Tag not working

### ISSUE THREAD

**Issue by mare-on** [sekwah41/Advanced-Portals#82]
Hi,
I have a problem with using permission tag on my portal. I have this portal:
/portal create name:mt_mystiq destination:spawn command:"broadcast &6Player @player..." permission:essentials.broadcast

And here comes the problem, for my Moderators and Admins with broadcast permission in PEX, it works but for normal players without permission in PEX it not. Where is the problem?

I am using v0.0.35 with craftbukkit v1.12

**Comment by sekwah41** [comment]
the fact you they dont have the permission... the permission is to use the portal not to add for the command

**Comment by mare-on** [comment]
oh shit, ok so... that sucks. :/

**Comment by mare-on** [comment]
So I can not create this type of portals for normal players?
I don't understand why is the permissions tag here, useful only if players doesnt have access to all portals?

There is no option to allow players use commands on which they dont have permissions?
