### ISSUE TITLE
nether portal allowing pigman through

### ISSUE THREAD

**Issue by smmmadden** [sekwah41/Advanced-Portals#87]
I just started seeing pigmen coming through my AP with Nether Portal.  That portal (below) takes me to another world, not the nether.  So not sure if a recent BungeeCord or Spigot update in 1.12.1 changed something, but wanted to report it to you in case you have an idea what's causing it.
![image](https://user-images.githubusercontent.com/10309346/30193035-f3a0c1b4-9418-11e7-97a8-b7be91864852.png)

**Comment by sekwah41** [comment]
Ill have to listen to the spawn events, ive not had it though it could be the difficulty im on on the server. Ill have to test and check events that do it.

**Comment by smmmadden** [comment]
here is everything from my server.properties in case it is a setting there.  I've replaced actual port numbers with an * for security reasons to post here.
#Minecraft server properties
#Thu Sep 07 08:35:46 EDT 2017
spawn-protection=48
max-tick-time=60000
query.port=****
server-name=TmTmc The Hub
generator-settings=
force-gamemode=true
allow-nether=true
gamemode=0
broadcast-console-to-ops=true
public=true
enable-query=true
player-idle-timeout=3600
difficulty=3
spawn-monsters=true
op-permission-level=4
pvp=true
grow-trees=true
snooper-enabled=true
level-type=DEFAULT
hardcore=false
enable-command-block=true
max-players=50
network-compression-threshold=256
resource-pack-sha1=
max-world-size=29999984
server-port=*****
debug=false
verify-names=true
server-ip=127.0.0.1
spawn-npcs=true
allow-flight=true
level-name=thehub
view-distance=10
server-id=unnamed
resource-pack=
spawn-animals=true
white-list=true
generate-structures=true
max-build-height=256
online-mode=false
level-seed=-6124344959755810533
prevent-proxy-connections=false
enable-rcon=false
motd=\u00A7dTmTmc \u00A72The Hub \u00A7eVersion 1.12.1\n\u00A7bResource Pack Required\: any

**Comment by sekwah41** [comment]
Fixed in next update
