### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by peccator085** [sekwah41/Advanced-Portals#91]
I am using the Multiverse plugin and the bungee cord server experimentally.
My purpose is to create a server that uses several computers and uses them to some extent.
But this has challenges. Moving player data between servers plug-in was easily found, but as far as I know there is no plug-in that meets the following conditions.
Condition 1 Portal Plugin
Condition 2 Plug-in operating with version 1.12.X
Condition 3 It is possible to make an exit at a specific position of a specific world of a specific server
Can not you do this with this plugin?

**Comment by sekwah41** [comment]
The easiest way to set this up and have this working well would be with a bungee plugin. I will take a look at writing a bungee plugin to communicate data to the servers.

**Comment by sekwah41** [comment]
This is the same as #139 and although this was firs the other has a clearer overview whereas this has more precise stages with the conditions. Although in terms of player data I wont be adding movement of inventories.
