### ISSUE TITLE
Survival Portals?

### ISSUE THREAD

**Issue by CompTechHS** [sekwah41/Advanced-Portals#93]
Hey, is there a way that I can use these sort of like nether portals in that I can have a multiverse world, and I can make a portal design for said world, and then whenever a player can gather the materials to make the portal, they can make it and turn it on, and then travel to said world? Let me give my scenario. Currently, I am working on setting up a server that uses custom world generation for the main world itself (its a survival server.) And I want to use Exotic Garden but you cant use Exotic Garden with custom terrain, so my idea was to have a "farm dimension." In this dimension, exotic garden plants exist. The way you would get there is the player would make a portal whether it be making a nether portal shape with hay bales and then surrounding it with wheat crops, or whatever portal design, and they can activate the portal somehow and then use it to teleport them to the world? I feel like there must be a way to do this, but I'm not sure how, so any help[ is much appreciated, thanks!

**Comment by sekwah41** [comment]
Sadly this isn't the sorta plugin that this is. The way the portals are detected in this plugin is soley location based and not off the portal event. Though the sorta plugin you have described would not be hard to code. A basic yml file of world redirect locations and world scales. Though if you were to make custom structures detected that would take a fair bit more code in comparison depending on how you would want it.

**Comment by sekwah41** [comment]
One way that would be possible but not suggested would be as an addon for this but if it lost track of the specific portals somehow it would start to get a little strange. The best way id suggest going about this is to ask someone to program a custom portal plugin which shouldnt cost you much tbh.
