### ISSUE TITLE
Add permissions error message

### ISSUE THREAD

**Issue by Xorgon** [sekwah41/Advanced-Portals#94]
I recently encountered a problem where a player couldn't build in a region and we didn't know why. In the end we figured out that it was Advanced-Portals. Could an error message be added to alert the player that they can't build due to not having permissions and add some permissions documentation?

e.g. "[Advanced-Portals] You can't build here!"

Thanks!

**Comment by Xorgon** [comment]
Added permissions page to the Wiki: https://github.com/sekwah41/Advanced-Portals/wiki/Permissions

**Comment by sekwah41** [comment]
There is a protection border in the config. Thanks for saying about the message. It makes it clear what is going on.

**Comment by Xorgon** [comment]
I added the required code (using your PluginMessages prefix and everything) in #95.
