### ISSUE TITLE
tamed animals

### ISSUE THREAD

**Issue by seema84** [sekwah41/Advanced-Portals#96]
can you please support "all" tamed animals?(parrot,wolf,cat)

**Comment by sekwah41** [comment]
Would be best to add a tag to allow this or an option rather than the main plugin allow it. Else people may start moving pets between worlds and other problems

**Comment by seema84** [comment]
thats right

**Comment by seema84** [comment]
please don't forget

**Comment by seema84** [comment]
i think leashed and when they move through the portal could be enough
(and ridable but this is already working)

**Comment by sekwah41** [comment]
Only on short distance or to loaded chunks, its wierd

**Comment by sekwah41** [comment]
Also i think to other worlds, same world it seems to hate it

**Comment by seema84** [comment]
actually it is enough if you could push them through the portal
i think this easy to implement

**Comment by sekwah41** [comment]
Due to how chunks load and unload and not wanting to toy with this too much (same for mounted entities though will look more into that) I will be avoiding this. Sorry :(
