### ISSUE TITLE
Users can't build around portal

### ISSUE THREAD

**Issue by ContemptGaming** [sekwah41/Advanced-Portals#99]
I use Multiverse 2 for world generation, and forgot to link a Nether world together with it. So I used Advanced Portals to make a portal link between that and another Nether world. Now, my users can't build around the portal unless they're OPed. (It's a survival game mode, and the portal is inside their house. So you can see why they need to build around it.)

I used /portals create without any special permissions. Any ideas?

**Comment by sekwah41** [comment]
Its part of the protection region on the portal in the config file for the plugin. Change it to 0 if you want or 1 for a short area.
